### PR TITLE
Restructure the Slint reference documentation

### PR DESCRIPTION
**Pull request by tronical**
This change turns the "Slint Language Reference" into the "Slint Reference" to make room for additional topics in the future.

New structure:

Slint Reference:
 * Introduction
   * Getting Started
 * Language Reference
   * Introduction
   * Concepts
   * Builtins
   * Syntax
 * Recipes & Examples
   * Custom Control Introduction
   * Animation Examples
   * States Examples
   * Layout Examples
   * Global Callbacks
   * Custom Widgets
 * Advanced Topics
   * Debugging Techniques
   * Selecting A Widget Style

In the future the list of supported platforms would go under "Introduction".

### CODE REVIEW

**Comment by tronical** [comment]
Screenshot 2023-08-14 at 15 23 32

**Comment by tronical** [comment]
Screenshot 2023-08-14 at 15 28 49

**Comment by tronical** [comment]
Going to rebase this on top of the license header check fixes.

**Review by ogoffart — APPROVED** [review]
I like the new structure.

Some stuff i'd have done differently:
 - I would re-order Builtins after syntax.
 - I'd put the "Widgets" in its own chapter, after "builtins" instead of nested inside it.

**Comment by tronical** [comment]
Both excellent points that I fully agree with. I'll make a follow-up change for that.

**Comment by tronical** [comment]
-> https://github.com/slint-ui/slint/pull/3270

**Pull request merged**
