### PR TITLE
Feature/weather demo improvements

### PR DESCRIPTION
**Pull request by Justyna-JustCode**
The changes:
1. A small fix and improvement.
2. New "open_weather" feature that allows to avoid compiling OpenSSL for Android when it's not needed.
3. Adding the demo into the apk build.

### CODE REVIEW

**Review by tronical — APPROVED** [review]
Thanks! I'll merge this once the CI is green and do a nightly - then the APK is soon available to try :)

**Comment by tronical** [comment]
Running now at https://github.com/slint-ui/slint/actions/runs/10110174044/job/27959566091

**Comment by tronical** [comment]
New attempt: https://github.com/slint-ui/slint/actions/runs/10110719849 :)

**Comment by tronical** [comment]
I tried running the apk from https://github.com/slint-ui/slint/actions/runs/10111631734 in the emulator, but sadly it crashed (with no usable backtrace).

**Comment by Justyna-JustCode** [comment]
Hmm... interesting. I was testing the app on my phone and it worked just fine.
Let me take a look on Monday!

**Pull request merged**
