### PR TITLE
Prepare Rust generator for libraries

### PR DESCRIPTION
**Pull request by jpnurmi**
This PR paves the road for AOT-compiled component libraries that must be able to generate enums, structs, etc. regardless of whether they are used, or if there's a public component at all.

The idea is that the `ModuleGenerator` trait is implemented in a different way for library modules:
- use library name as module ident (instead of component name)
- generate structs and enums from `Document::inner_types` (instead of `Component::used_types`)
- optionally, generate a public component if it exists (instead of generating nothing when it doesn't)

In pseudo:
```rust
mod slint_generated#module { // component vs. library name
    #(#enums_and_structs)* // used (app) vs. all (lib)
    #(#sub_components)*
    #public_component // mandatory (app) vs. optional (lib)
    #(#globals)*
    #version_check
}
pub use slint_generated#module::{#(#public_ids),*}; // component, enums, structs, globals
```

The proposed next steps would be:
- keep track of types imported from libraries and use those types from library crates
- add compiler configuration for libraries

See also:
- #154
- #3523

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks!
If I understand this correctly, this adds a `generate_library`  function. How do you imagine this function will be called.
Would that be a flag in slint-build ? 

> * generate structs and enums from Document::inner_types (instead of Component::used_types)

I think we only want to use the one that are exported, or used by exported components

This is going to be hard to know later when generating something that use a library if a struct need to be generated or not and if it needs to be used through a path or not. We'll need to find a solution for that.  But it seems wrong to generate all the struct, even the ones that are only internal and not used by name anymore because they were not used.

----

Another question worth asking is how much exposing generated component in the crates's public API will make some of our current internal fixed.  I guess the generated things should all be `#[doc(hidden)]` in a module that has a doc that says something like "this module content contains code generated by Slint macro and should only be used by other Slint macro of the same version in other crates".

**Comment by jpnurmi** [comment]
> Thanks! If I understand this correctly, this adds a `generate_library` function. How do you imagine this function will be called. Would that be a flag in slint-build ?

I was experimenting with such public API in slint-build:
```rust
// mylib/build.rs
fn main() {
    // for convenience, picks the name from CARGO_PKG_NAME
    slint_build::compile_library("ui/lib.slint").unwrap();
}
```

Which would be basically the same as:
```rust
// mylib/build.rs
fn main() {
    slint_build::compile_with_config(
        "ui/lib.slint",
        CompilerConfiguration::new().as_library("mylib".to_string())
    ).unwrap();
}
```

These could be added as the last step after the other missing bits (library lookup from #3523, and library type tracking) are in place.

> > * generate structs and enums from Document::inner_types (instead of Component::used_types)
> 
> I think we only want to use the one that are exported, or used by exported components

Ahh, I didn't realize it included internal enums because my test library only had exported structs and enums. :man_facepalming:

**Comment by tronical** [comment]
> > * generate structs and enums from Document::inner_types (instead of Component::used_types)
> 
> I think we only want to use the one that are exported, or used by exported components

I agree, I'd also lean towards exported and used_types.

> This is going to be hard to know later when generating something that use a library if a struct need to be generated or not and if it needs to be used through a path or not. We'll need to find a solution for that. But it seems wrong to generate all the struct, even the ones that are only internal and not used by name anymore because they were not used.

If we generate used and exported types, is there anything missing for consumers of the library? Can you elaborate what kind of use-case we need to find a solution for?

> Another question worth asking is how much exposing generated component in the crates's public API will make some of our current internal fixed. I guess the generated things should all be `#[doc(hidden)]` in a module that has a doc that says something like "this module content contains code generated by Slint macro and should only be used by other Slint macro of the same version in other crates".

I agree, to start with this needs to be fixed to the slint version exactly.

**Comment by ogoffart** [comment]
> If we generate used and exported types, is there anything missing for consumers of the library? Can you elaborate what kind of use-case we need to find a solution for?

For example, the `struct TextStyle`  defined in the fluent style, it is likely (indirectly) used by the library so it is going to be generated there.
It is also likely to be used by the application.
Will both the application and the library generate their own struct for `TextStyle` ?  That will work unless they share somehow some structures that uses them.

Also how is it going to work with globals used in the style?  What if there are two libraries imported?

**Comment by tronical** [comment]
> > If we generate used and exported types, is there anything missing for consumers of the library? Can you elaborate what kind of use-case we need to find a solution for?
> 
> For example, the `struct TextStyle` defined in the fluent style, it is likely (indirectly) used by the library so it is going to be generated there. It is also likely to be used by the application. Will both the application and the library generate their own struct for `TextStyle` ? That will work unless they share somehow some structures that uses them.

How would the library or application use `TextStyle` from the fluent style right now, either explicitly or implicitly?

> Also how is it going to work with globals used in the style? 

This part is tricky indeed, since currently we assume that we always have access to the "root", but for a library that "root" doesn't exist, or we have to invent it. Perhaps we could have a `LibraryXXGlobals` struct that has all the globals the library defines. The application has that as a field. But we somehow need to pass that every time an item tree is instantiated from that library. So if library1's `Button` is only ever instantiated through library2 but not app, then somehow app needs to pass `Library1Globals` through library2, so that it can reach library1. Urgh.

> What if there are two libraries imported?

Can you elaborate?

**Comment by jpnurmi** [comment]
One won't get far with only structs and enums so let's put this on hold until there's a way to share globals
- #784

**Pull request closed without merging**
