### PR TITLE
fix bug: error[E0063]: missing field `load_substitutions`

### PR DESCRIPTION
**Pull request by jhq223**
…ontSettings`

  --> D:\.env\rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-core-1.3.0\software_renderer\fonts\systemfonts.rs:29:29
   |
29 | ...                   fontdue::FontSettings { collection_index: font_index, scale: 40. },
   |                       ^^^^^^^^^^^^^^^^^^^^^ missing `load_substitutions`

### CODE REVIEW

**Comment by jhq223** [comment]
I am a beginner, and I encountered this issue during compilation. I tried to fix it, but it doesn't seem to be working correctly.

**Comment by jhq223** [comment]
```bash
error[E0063]: missing field `load_substitutions` in initializer of `FontSettings`                                                          
  --> D:\.env\rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\i-slint-core-1.3.0\software_renderer\fonts\systemfonts.rs:29:29    
   |
29 | ...                   fontdue::FontSettings {
   |                       ^^^^^^^^^^^^^^^^^^^^^ missing `load_substitutions`

For more information about this error, try `rustc --explain E0063`.                                                                        
error: could not compile `i-slint-core` (lib) due to previous error   ```

**Comment by ogoffart** [comment]
Thanks for the Pull Request!

The bug was a temporary bug caused by the release of fontdue 0.7.4. which contained a breaking change.
But that release is now yanked. So the compilation error is fixed.
They released fontdue 0.8 with the changed API. So we should still get this change in, but it should also include the update to fontdue 0.8 in the Cargo.toml.

**Review by tronical — APPROVED** [review]
I've pushed a few fix-ups. Will merge it now. Thanks for the PR! ❤️

**Pull request merged**
