### PR TITLE
Second stage of cleaning up the export handling of the slint root component

### PR DESCRIPTION
**Pull request by tronical**
Commit 24dcef5fed2b53e6d1f65ba0fb5db9de9d657bf2 added a warning for the implicit export of last component. For 1.0, this commit makes it so that the root component is determined by the last export in the file.

### CODE REVIEW

**Comment by tronical** [comment]
Marked as draft as this shall not go in until the next patch release is out.

**Comment by ogoffart** [comment]
Should there not be a warning anyway if the last component is not exported ?
Because it cannot really be used.  (unless it is only used with the preview)

**Comment by tronical** [comment]
Can you elaborate? What warning text do you have in mind for this:

```
export component Foo {
    // ...
}

component Bar {
     // ...
}
```

**Comment by tronical** [comment]
Perhaps a warning could be issued if the root file exports multiple components, until we have implemented support for it?

**Comment by ogoffart** [comment]
Maybe a unused component or something?

**Comment by tronical** [comment]
So if the last component in the file is not exported and not used, there should be a warning? Ok. What would the text be? "warning: component is unused and not exported" ? Maybe that's not just for the last component but any unused one?

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
