### PR TITLE
core: implement FromIterator for VecModel

### LINKED ISSUE #5879: `VecModel` should implement `FromIterator`
It would be useful, if `VecModel` implemented `FromIterator` ([like `Vec` does](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-FromIterator%3CT%3E-for-Vec%3CT%3E)). Then, one could simply `some_iter.collect()` into a `VecModel`.

### PR DESCRIPTION
**Pull request by crai0**
This PR implements the `FromIterator` trait for `VecModel` as requested in #5879.

Closes #5879

### CODE REVIEW

**Comment by Enyium** [comment]
I think the item type should be `T` (as elsewhere in the same file) and the iterator type `I` (as customary in `std`).

**Comment by crai0** [comment]
I used the type parameters as they are defined in `std`:
```rust
pub trait FromIterator<A>: Sized {
    /// Creates a value from an iterator.
    ///
    /// See the [module-level documentation] for more.
    ///
    /// [module-level documentation]: crate::iter
    ///
    /// # Examples
    ///
    /// ```
    /// let five_fives = std::iter::repeat(5).take(5);
    ///
    /// let v = Vec::from_iter(five_fives);
    ///
    /// assert_eq!(v, vec![5, 5, 5, 5, 5]);
    /// ```
    #[stable(feature = "rust1", since = "1.0.0")]
    #[rustc_diagnostic_item = "from_iter_fn"]
    fn from_iter<T: IntoIterator<Item = A>>(iter: T) -> Self;
}
```

I think they use `T` instead of `I` because `iter` is not actually an iterator but some type implementing `IntoIterator`. I've got nothing against changing it, though.

**Comment by Enyium** [comment]
> I used the type parameters as they are defined in `std`:

Oh yeah. I have not idea why they chose this mapping. Personally, I currently find it incoherent and wouldn't follow it in this case.

> I think they use `T` instead of `I` because `iter` is not actually an iterator but some type implementing `IntoIterator`.

`Vec<T>` [uses](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.from_iter) `I` for the `IntoIterator` argument:

```rust
fn from_iter<I>(iter: I) -> Vec<T>
where
    I: IntoIterator<Item = T>,
```

`Vec` and many other types use `A` for the `Allocator`.

If you do [a general search](https://doc.rust-lang.org/std/iter/trait.FromIterator.html?search=IntoIterator) in `std` and check the "In Parameters" list, most often they use `I` for the iterator and `T` for the item type, if they don't have two distinct near-iterators (like with `zip()` or `chain()`, in which case they use `A` as well as `B`). But, disappointingly, they *sometimes* even just switch them and use `I` for the item type and `T` for the near-iterator.

**Comment by crai0** [comment]
Alright, I renamed the type parameters. It's definitely cleaner/more consistent this way, I agree.

**Pull request merged**
