### PR TITLE
Redo the 7guis crud example

### PR DESCRIPTION
**Pull request by lukas-jung**
This is the current state of the 7guis crud example.

I also moved the single 7guis examples to different folders and added an 's' to 7gui, since that is the official name.

The filtering model is still specialized to this example, but I want to get feedback before trying to generalize it.

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]
Great.

I think this is good enough.

That said, inserting and removing in the middle of a vector many times is not really efficient. It would be better to do it in one pass.  But since i think the Repeater will anyway react to row_added and row_removed and do the same, it it inneficient anyway. So this is good for now and we can do optimization if one need to store many items.

**Comment by ogoffart** [comment]
If you rename the folder, there is a few location in readme and stuff that need to be updated.  Also a symlink in tests/cases

**Comment by ogoffart** [comment]
What's the reason why you moved the files in different folder btw?
I was thiking having all the files together named  foo.slint and foo.rs  (there can be several binaries declared in Cargo.toml)

**Comment by lukas-jung** [comment]
> What's the reason why you moved the files in different folder btw? I was thiking having all the files together named foo.slint and foo.rs (there can be several binaries declared in Cargo.toml)

I thought it was just in one folder, because until now the examples consisted only of slint files.
since that changes now i adapted it to the other examples (one folder per example).

**Comment by ogoffart** [comment]
I think that a single folder with all the files named  `foo.slint` and `foo.rs` is simpler. Or do you think it is simpler with one directory per sub-project?

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
