### PR TITLE
Implement upgrade_in_event_loop for no_std

### PR DESCRIPTION
**Pull request by jturcotte**

### CODE REVIEW

**Comment by jturcotte** [comment]
Please note that I'm removing the `Send + 'static` constraint from `func` in no_std.

I feel bad that this is now behaving oddly in relation to `invoke_from_event_loop`, if this matters then we'd need to also split its implementation for no_std.

My understanding is that you generate the doc with std enabled and that this one will just be ignored.

**Comment by jturcotte** [comment]
Humm now I'm wondering if the proper solution isn't to wrape `upgrade_in_event_loop` in my application.

The use case is that my backend is in a separate thread, but since I don't have (or need) threads in no_std environments then I have to move the backend to the main thread.

Implementing it synchronously is also a bit odd since in WASM builds this function will post to the event loop instead. So I'm starting to think that maybe it should just call invoke_from_event_loop also for no_std.

**Comment by ogoffart** [comment]
it feels like the upgrade_in_event_loop should still be "queued" to the next iteration

**Comment by jturcotte** [comment]
Seems like I'd need to provide an implementation for new_event_loop_proxy to test this in my no_std application and would otherwise be an unnecessary overhead when you're able to control the main loop. It is in my case at least since I don't have reentrancy problems yet, so I'll just wrap upgrade_in_event_loop to avoid it for no_std.

I'll probably close this since I don't think it makes sense to implement it without providing a reason and an example or implementation of a lightweight implementation for new_event_loop_proxy.

Or do you think that it would make sense to document that invoke_from_event_loop and upgrade_in_event_loop are not really supported for no_std until then?

**Comment by ogoffart** [comment]
Maybe `upgrade_in_event_loop`  don't need to be gated.  `invoke_from_event_loop` is also there in no_std. So we probably can simply remove the feature gate for that function.

**Comment by ogoffart** [comment]
https://github.com/slint-ui/slint/pull/2425 should replace this PR

**Pull request closed without merging**
