### PR TITLE
cleanup widgets according to upcoming code guidelines

### PR DESCRIPTION
**Pull request by FloVanGH**
It's marked as draft because it touches now only a few files to check how the suggestion for the Slint code style from @ogoffart would looks like (check #3768).

1. Public interface  (public properties / callbacks / public functions)
3. private interface (private properties / private functions)
4. property setters
5. states (as they are kind of property setters / animations)
6. children

I've added an order for the public properties 

1. in
2. out
3. in-out

I personally not happy with the result of that code style. Yes the profit is you can see the whole public api in the start of the component, but for my taste I think the code in common looks much more unclear. But that's my personal feeling. What the majority says counts, because I will not the only person writing Slint code and others will use the guidelines also for their projects.

### CODE REVIEW

**Comment by ogoffart** [comment]
I don't have strong opinion about styling other than it's nicer to keep the public interface on top and the implementation details after that.

> but for my taste I think the code in common looks much more unclear. But that's my personal feeling.

Maybe it's just a question of habit that will disappear after using it for a while?

**Comment by FloVanGH** [comment]
Thank you @hunger. But I will continue to stick with the guideline version that most agreed with. I'm almost done with the adjustments for the widgets.

I agree that the most important part is that we have a guideline at ensure consistency in our code base and as template for people using Slint. 

Therefore I think we should soon add also the guidelines to the documentation after the update on the codebase is finished.

**Comment by FloVanGH** [comment]
The cleanup for the widgets are done.

### Upcoming PRs

* Code cleanup examples
* Code cleanup in documentation
* Add guidelines to documentation

We need a good place for the Slint code guidelines in the documentation. Suggestions?

**Comment by tronical** [comment]
> We need a good place for the Slint code guidelines in the documentation. Suggestions?

If it's for internal use, then say `docs/guidelines.md`. If it's meant for users of Slint, then I'd say into the "Slint Language Documentation" - unless it justifies its own "book". What would be the title if it were for users of Slint? Or differently put:

What would the first intro paragraph of the public documentation for this look like? (that will tell us a lot where this goes and how it should be called)

**Comment by FloVanGH** [comment]
> > We need a good place for the Slint code guidelines in the documentation. Suggestions?
> 
> 
> 
> If it's for internal use, then say `docs/guidelines.md`. If it's meant for users of Slint, then I'd say into the "Slint Language Documentation" - unless it justifies its own "book". What would be the title if it were for users of Slint? Or differently put:
> 
> 
> 
> What would the first intro paragraph of the public documentation for this look like? (that will tell us a lot where this goes and how it should be called)

I think for both. We should reference it in our contribution guideline. Because we use for our Slint codebase. But it should also be public available as suggestion. I think there are enough people that are thankful about a suggestion how they can structure their Slint code, without the need to define an own one.

I think a whole book is to much for the guidelines. Maybe it can be a chapter in the language book (as suggestion).

**Comment by FloVanGH** [comment]
For example after the guidelines are written down on a public place, I want to reference it in the contribution guidelines of coop, and I think maybe some others want that too.

**Comment by tronical** [comment]
Sounds good, this matches what I was thinking. The term however that comes to my mind is “Best Practices”.

**Comment by FloVanGH** [comment]
> Sounds good, this matches what I was thinking. The term however that comes to my mind is “Best Practices”.

“Best Practices” sounds good. Only in our contribution guidelines it should me linked as mandatory.

**Review by tronical — APPROVED** [review]

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
