### PR TITLE
Change properties of Palette to in-out

### PR DESCRIPTION
**Pull request by ghost**
* Changes brush properties of `Palette` from `out` to  `in-out`
* This is needed to fix test in #6381
* Give user minimal capabilities of custom color styling

### CODE REVIEW

**Comment by ogoffart** [comment]
I'd say `out` is correct. I'm not sure we want to let users change the Palette like this, do we?
There can be other ways to fix the test.
If we go this route, we can't go back.

So the question is: 
1. Do we want Slint user to be able to change the palette color with something like `Platte.alternate-background = #123;`?
2. Should our styles support that and be garenteed to use that palette? As implemented currently, the Qt style doesn't (one'd need to call `setPalette` on the QWidget when these properties get changed)

**Comment by hunger** [comment]
I guess it depends a lot on how we want our widgets to be used.

So far we seem to go for "looks native (as we define that;-) no matter what". For that `out` properties make more sense.

If we want to go for "users can actually change widgets when it makes sense for their application", then it makes a lot of sense to me to be able to change the palettes. We should have a way to get the default palette back though.

**Comment by tronical** [comment]
The slint compiler uses (or will use) the `Palette` to affect the default look of `Text` and `TextInput`. This means it affects users who make their own widget sets, and that also means that those users need to be able to customise that without too much hassle (that being a `component MyText inherits Text { default-text-color: MyPalette.foreground }` kind of workaround).

We're blurring the lines between the cross-platform standard widget sets and custom UIs. If we keep a certain blur (that's fine, there are common concepts), then we need to serve both at the same time. We could also consider making a stricter separation and encapsulating the standard widgets more. That means `Palette` from `std-widgets.slint` would remain a concept strictly for the standard widgets.

I don't see how to draw a stricter line though, due to the `Text` defaults. Perhaps there's a way? Have a `Label` in `std-widgets.slint`?

So the easy way out is to blend `Palette` into both sides and permit free mutation. But I feel that's ignoring what might be a bigger issue. So I think we should take a quick step back and make sure that we're overall aligned still so that this (and other similar changes) continue to make sense. I'd prefer the use of a lower-latency forum to discuss this, achieve consensus quicker, and record the result.

**Comment by hunger** [comment]
I would love to see something that @FloVanGH proposed earlier: Base widgets that are easy to customize and then a set of custom widgets built from those. E.g. a base button that accepts any child and draws itself "around" those children and then the standard button we have right now built from that. The base widgets give us the flexibility users will need and the standard widgets built a native-looking UI on top of that.

**Pull request closed without merging**
