### PR TITLE
live-preview: Fix syntax errors in api.slint

### PR DESCRIPTION
**Pull request by hunger**
Sometimes I am surprised my code works.

Reformat the entire thing while at it.

### CODE REVIEW

**Comment by hunger** [comment]
This is uncontroversial enough to not wait for review.

I wonder how that ever worked though.

**Comment by tronical** [comment]
What was the syntax error?

**Comment by ogoffart** [comment]
You are reverting https://github.com/slint-ui/slint/pull/5859 though.

**Comment by hunger** [comment]
The slint-lsp lights up like a Christmas tree whenever I open that file, and I open that a lot.

I'll happily revert back to named args once the LSP is updated to work with that.

**Comment by ogoffart** [comment]
You just have to define the env variable for experimental features

**Pull request merged**
