### PR TITLE
Changed dark-color-scheme property to in-out

### PR DESCRIPTION
**Pull request by FloVanGH**

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]

**Comment by ogoffart** [comment]
> Wouldn't it make more sense to first make StyleMetrics public before using it in more of our examples? 

I tend to agree.  But it's used more than once so the ship has sailed. Grep for it and see that many of our example, including the gallery uses it.

But yeah, we need somehow to polish this API.

IMHO we should maybe expose a full palette with all commonly used color:  See also https://github.com/slint-ui/slint/issues/3687
Not sure if the `dark-color-scheme` property belong there and if it should be `in-out` though.

**Comment by ogoffart** [comment]
As for this PR, I think it "solves" a problem and make it nice in our demo on our website, so there is an immediate gain, and it is already used in user code[1], so i'd go for it.

[1] https://github.com/search?q=StyleMetrics%20%20path%3A*.slint%20-repo%3Aslint-ui%2Fslint%20-is%3Afork&type=code

**Comment by FloVanGH** [comment]
I use `StyleMetrics` for a long time now on the `coop_widgets` to read `dark-color-scheme` value from the system 😅. 

I also like the behavior as eye catcher for the gallery. Maybe a comment in the code could help and we replace it after we have a final solution. I agree that this topic is also connected to https://github.com/slint-ui/slint/issues/3687 . And I think it's an important one and we should not wait to long. Give user public access to base style resources like `dark-color-scheme`, base brushes and base typography settings.  

After that it would be really great if we soon also give the user access to the full styling resources of styles. I think both uses cases are important for different users.

**Comment by tronical** [comment]
> > Wouldn't it make more sense to first make StyleMetrics public before using it in more of our examples?
> 
> I tend to agree. But it's used more than once so the ship has sailed. Grep for it and see that many of our example, including the gallery uses it.

Yeah. I don't want to stop the ship that has left the harbour, but I want to avoid it running into a bay of pirates, so course correction ;). In other words: I don't think that we should make it worse. (the name we can also still change, via aliases)

**Comment by FloVanGH** [comment]
A proposal about how we can providing style resources https://github.com/slint-ui/slint/issues/3687#issuecomment-1769046295. It is also be connected to this topic.

**Comment by FloVanGH** [comment]
I close this, because we will implement an other solution for this topic: check #3687

**Comment by tronical** [comment]
Re-opened in https://github.com/slint-ui/slint/pull/4701

**Pull request closed without merging**
