### PR TITLE
Fix pixelated Spyrosoft logo on the H7 screen

### PR DESCRIPTION
**Pull request by tronical**
Increase the default resolution so that the pre-rendered texture is less pixelated.

### CODE REVIEW

**Review by FloVanGH — APPROVED** [review]

**Comment by ogoffart** [comment]
Note that making it less pixelated on the H7 will make it more pixelated in the pico

**Comment by tronical** [comment]
Fair point. Any idea what we could do?

**Comment by ogoffart** [comment]
Short term, we could commit that in a branch special for that device

Long term, we shall try to have better const propagation in the compuler (including layout and stuff) and somehow figure out the size at compile time.

Also, implementing smooth scaling in the software renderer will be necessary

**Comment by tronical** [comment]
Ah yes, i can just push that into the h7 specific branch. Thanks :)

**Pull request closed without merging**
