### PR TITLE
Fix window always coming to the front on Ubuntu 20.04 when window properties change

### LINKED ISSUE #3280: Window being constantly in front
### Discussed in https://github.com/slint-ui/slint/discussions/3252

<div type='discussions-op-text'>

<sup>Originally posted by **JanDiederich** August 10, 2023</sup>
I have an application with constantly animated text, that breaks the Winit backend and the Qt backend. I tested both, but the result stays the same. The window is a constant topmost application, which can't stay in the background and constantly, annoyingly, workflow-stopingly, pushes itself into the topmost front.

How can I fix that?

My systems: Ubuntu 20.04.6 LTS 64 Bit and Raspberry Pi OS 64 Bit latest version.

Edit: As soon as I disable the animation, the window behaves normal. The "redraw" call, caused by the animation, seems to trigger it.</div>

### PR DESCRIPTION
**Pull request by tronical**
Only call set_window_level if the value changes.

Fixes #3280

### CODE REVIEW

**Comment by JanDiederich** [comment]
> Changes approved

Please, please, check this also with the Qt backend, I think the bug appears there also.

**Comment by tronical** [comment]
I checked with Qt and I can't reproduce the bug there.

**Comment by tronical** [comment]
For the record, this a clip how the issue reproduces with winit (before this patch) and how it works with Qt:

https://github.com/slint-ui/slint/assets/1486/466aa736-803f-483e-bfd6-20d5582741f2

**Comment by ogoffart** [comment]
> The latest Git commit fixes it, also with the Qt backend.

It doesn't touch the Qt backend.  I think the Qt backend is disabled on old Ubuntu because it doesn't have a version of Qt that's recent enough (Qt 5.15 is needed)

**Pull request merged**
