### PR TITLE
reduce rust generated file size

### PR DESCRIPTION
**Pull request by Guiguiprim**
A small suggestion to help reduce the size of rust generated files.

using `use slint::private_unstable_api::re_exports as sp;` should allow to safely qualify everything while keeping things shorter.

For the `todo` example:
- before 1_050_650 octets for 24_012 formatted lines
- after 934_049 octets for 23_032 formatted lines

This also makes the generated code more readable if needed.

### CODE REVIEW

**Comment by ogoffart** [comment]
This is great.   Did you measure an impact on the compilation speed?

**Comment by Guiguiprim** [comment]
> Did you measure an impact on the compilation speed?

I did not measure, I'm going to look at it.

Unrelated CI issues on `Install Qt`.

**Comment by Guiguiprim** [comment]
From a very scientific testing, I would say "no impact".

My protocol:
1. `cargo build --release -p todo` (build all deps)
2. `rm target/release/build/todo-*`
3. `time cargo build --release -p todo` (only generate code and build binary)

The results:
- with changes
    - usr time  101.39 secs
    - usr time  100.53 secs
- without changes
    - usr time  100.97 secs

**Comment by ogoffart** [comment]
Thanks!

**Pull request merged**
