### PR TITLE
enable scripts to access the length of arrays

### PR DESCRIPTION
**Pull request by jamesblacklock**
This is my first shot at implementing a "length" property for arrays. The Rust version works, but I'm not sure about the C++ version. I'm really just looking for thoughts or comments.

### CODE REVIEW

**Comment by jamesblacklock** [comment]
Because the length is read only and it will only change when the whole model gets replaced, does it actually need to notify? 🤔

**Comment by jamesblacklock** [comment]
@ogoffart I believe this should pass all tests now. Is there an intention to merge this branch?

**Comment by jamesblacklock** [comment]
I needed to add license header to new file. That is done now.

**Comment by ogoffart** [comment]
Yes, I'll have a closer look tomorrow

**Pull request merged**
