### PR TITLE
Make the parentheses optional in if else statement

### LINKED ISSUE #4062: `if` statements shouldn't require both parentheses and curly braces
My understanding is that having neither can't be properly parsed, but that having either parentheses or curly braces make it unambiguous where the conditional expression ends.

Requiring both, however, feels unnecessary and clutters the code.

Right now [this works](https://slint.dev/releases/1.3.2/editor/?snippet=export+component+Demo+inherits+Text+%7B%0A++++text%3A+%22NOT+PRESSED%22%3B%0A++++TouchArea+%7B%0A++++++++pointer-event%28e%29+%3D%3E+%7B%0A++++++++++++if+%28e.kind+%3D%3D+PointerEventKind.down%29+%7B%0A++++++++++++++++%2F%2F+Let%27s+pretend+that+this+triggers+a+backend+callback.%0A++++++++++++++++parent.text+%3D+%22PRESSED%22%3B%0A++++++++++++%7D+else+%7B%0A++++++++++++++++parent.text+%3D+%22NOT+PRESSED%22%3B%0A++++++++++++%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A&style=native):

```js
pointer-event(e) => {
    if (e.kind == PointerEventKind.down) {
        root.down();
    } else {
        root.up();
    }
}
```

but I think that it would be cleaner and more consistent to allow either of these:

```js
pointer-event(e) => {
    if e.kind == PointerEventKind.down {
        root.down();
    } else {
        root.up();
    }
}
```

### OR

```js
pointer-event(e) => {
    if (e.kind == PointerEventKind.down)
        root.down();
    else
        root.up();
}
```

Because the conditional element `if` doesn't require parentheses [anymore](https://github.com/slint-ui/slint/issues/466), it would probably be better to enable the former, if any.

### PR DESCRIPTION
**Pull request by Chen1Plus**
resolve #4062 

Not complete, this will break formatter.
It seems like formatter can't identify if without parentheses.

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks for the PR.

If I paste the code that you try to format in a .slint file and try to compile it, i get the following error:
```
error: Syntax error: expected '}'
 --> tmp/foo.slint:2:20
  |
2 | A := B { c => { if !abc{nothing}else   if  true{if 0== 8 {}    } else{  } } }
  |                    ^
```

So it looks like the formater fails to format because it wasn't parsed properly in the first place
The bug is not in the formatter, but in the parser.

That is because `parse_if_statement` is not even being called for this code.

That is because the code in `parse_statement` expect a parenthesis after the `if`
https://github.com/slint-ui/slint/blob/01336be8714c12e8b28fac53356d34f47f66bb9f/internal/compiler/parser/statements.rs#L27

We could remove the requirement for parentheses there.

The thing is that there is no keyword in slint so one can have `property <bool> if;` or `if := Rectangle { }`
And this would break code like this:  `xxx: if;` or `xxx: if.bar;`
But i'm pretty sure nobody has a property called if at this point.

It is slightly more complicated, but the solution can be:
 1. just remove the test for the `(` in parse_statement. That's easy and can worry about properties and element with `if` later.
 2. Try to parse an expression, and if that fails roll back. This is the most correct but also most complicated solution because we don't have way to rollback at this point.
 3. instead of `(`, try to match any token that can start an expression. So `(`, `!` and all unary opps, identifiers, and maybe i miss some.
 4. instead of matching for `(`, try to match for token which are not starting an expression for sure. For example `.` or `;`. And also maybe or `,` or `)`.  That's actually what i'd do.


Please copy the test  that is in tests/cases/conditional/stm.slint  into tests/cases/conditional/stm2.slint  and remove the parentheses, so we have test for the non-parentheses if.
You can also extend the test to include things that have property or an element named `if`.


Thanks again for contributing to Slint 🤗

**Comment by Chen1Plus** [comment]
thanks for explanation and support

**Review by ogoffart — COMMENTED** [review]
Thanks for the change. Looks good to me.

**Review by ogoffart — APPROVED** [review]
Actually maybe there is some documentation that needs adjustments

**Pull request merged**
