### PR TITLE
Internalize hack for dynamic translations change so that it also works for Rust apps

### PR DESCRIPTION
**Pull request by tronical**

### CODE REVIEW

**Comment by tronical** [comment]
I'm expecting resistance on this one ;-)

**Review by ogoffart — COMMENTED** [review]
AFAIK, the code added is not called from C++ when translations changes.
So it needs to be done from  `mark_all_translations_dirty` instead

**Comment by ogoffart** [comment]
(ideally this would be in gettext-rs / gettext-sys, but since it seems that these crate are no longer maintained (cf https://github.com/Koka/gettext-rs/pull/106 ) then i guess it's fine to do the workaround in our crate :-/ )

**Comment by tronical** [comment]
> AFAIK, the code added is not called from C++ when translations changes. So it needs to be done from `mark_all_translations_dirty` instead

Good point. Fixed.

Ah yeah, I agree - it sucks to have this here.

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
