### PR TITLE
live-preview: Add buttons to hide sidebars

### PR DESCRIPTION
**Pull request by hunger**
Outside of edit mode:

Screenshot from 2024-09-10 12-44-05

In edit mode:

Screenshot from 2024-09-10 12-44-18

### CODE REVIEW

**Comment by NigelBreslaw** [comment]
Maybe for now it's better to just have a button for hiding the widgets on the left, but don't make it possible to hide the properties on the right. Two buttons is too much. Also you can still get rid of everything via the interact view.

**Comment by hunger** [comment]
I found slightly better matching icons!

image

**Comment by hunger** [comment]
@szecket suggested to hide the two buttons when not in Edit mode. I'll leave that out for now as that would move the Edit/Interactive toggle around.

**Comment by szecket** [comment]
and as soon as I can edit this stuff and push things I'll move the buttons so we can hide them without moving things around

**Pull request merged**
