### PR TITLE
Update corrosion to v0.3.0

### PR DESCRIPTION
**Pull request by jschwe**
Update Corrosion to v0.3-beta.
Works locally, hopefully also in your CI.

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks @jschwe for your work in corrosion. What you're doing is awsome.

The CI is failling in the cpp_package_test:

```
  CMake Error in CMakeLists.txt:
    IMPORTED_LOCATION not set for imported target "slint-cpp-shared"
    configuration "Release".
``` 

This is the step that tries to compile the example using the binary package from the previous step.
the previous step has done a `cmake --build . --config Debug --target package` and we're unpacking this package, setting the CMAKE_PREFIX_PATH env cariable, and then building the example with it.

Note that the package is build in Debug and the example are then built in Release mode.
This is maybe the problem.

**Comment by jschwe** [comment]
> This is the step that tries to compile the example using the binary package from the previous step.

Does this step perhaps use `SlintConfig.cmake`? If yes then this commit should already fix it, otherwise I'd try reproducing the build step locally. 

Corrosion sets the the IMPORTED_LOCATION properties at the end of the CMakeLists.txt where `corrosion_import_crate()` is called. To my knowledge there is no way around this, if corrosion wants to support setting the OUTPUT_DIRECTORY properties directly on the target and not only via the `CMAKE_OUTPUT_DIRECTORY` initialization. I think this limitation is because we have to tell CMake what files we are generating and BYPRODUCTS may not contain target specific generator expressions, so we must set IMPORTED_LOCATION at configure time.

The workaround here for slint is basically the same as what corrosion does - defer checking the properties until we know they are set. Corrosion registers its deferred functions first, so slints deferred function call will run afterwards. It's not particulary nice, but it should work.

**Comment by ogoffart** [comment]
> Does this step perhaps use SlintConfig.cmake?

Yes.  It basically assumes that the package was installed.
I believe you can reproduce it by calling `make install` and try to use the resulting package.

It looks like your attempt didn't fix the problem.

Maybe the `install(FILES $<TARGET_FILE:slint-cpp-shared> TYPE LIB)`  and all the other install stuff need to be delayed as well?

Note that this install step is a bit of a hack because the `install(TARGETS Slint slint-cpp ...)` doesn't install that library.

**Comment by tronical** [comment]
To build on what Olivier wrote, the GitHub action has the generated tarball after "make install". I downloaded it and looked into it. This is what I think is the relevant part from `SlintConfig.cmake`:

```cmake
add_library(slint-cpp-shared SHARED IMPORTED)
set_target_properties(slint-cpp-shared PROPERTIES IMPORTED_NO_SONAME;1;IMPORTED_LOCATION;${_IMPORT_PREFIX}/lib/libslint_cpp.so)
foreach(build_type Release RelWithDebInfo MinSizeRel Debug)
  string(TOUPPER "${build_type}" config_name)
  if(NOT("Debug" STREQUAL build_type))
    set_target_properties(slint-cpp-shared PROPERTIES MAP_IMPORTED_CONFIG_${config_name} "Debug")
  endif()
endforeach()
```

Something appears not to work with the config mapping maybe?

**Comment by jschwe** [comment]
> `    set_target_properties(slint-cpp-shared PROPERTIES MAP_IMPORTED_CONFIG_${config_name} "Debug")`

Commenting this line out or manually setting `IMPORTED_LOCATION_DEBUG` both fix the error for me locally. I guess an option would be to always define `IMPORTED_LOCATION_DEBUG` even if the dll was built with a single config generator?

**Comment by tronical** [comment]
Ah yes, that is the difference. With the previous version of Corrosion the debug build generates the debug import location:

```cmake
set_target_properties(slint-cpp-shared PROPERTIES IMPORTED_NO_SONAME;1;IMPORTED_LOCATION_DEBUG;${_IMPORT_PREFIX}/lib/libslint_cpp.so)
```

So in a way what we had there with the config mapping was a workaround. If newer corrosion sets `IMPORTED_LOCATION` straight for a single-config generator then maybe we don't need the mapping anymore?

Do you know what caused the change in Corrosion?

**Comment by jschwe** [comment]
> If newer corrosion sets IMPORTED_LOCATION straight for a single-config generator then maybe we don't need the mapping anymore?

Corrosion [now](https://github.com/corrosion-rs/corrosion/pull/213/) _always_ sets `IMPORTED_LOCATION`, even for Multi Config Generators. Not setting `IMPORTED_LOCATION` caused a CMake developer warning, so I think the new behavior is correct.

Previously corrosion passed around the build config(s) as a function parameter, while now it just checks `CMAKE_CONFIGURATION_TYPES` and `CMAKE_BUILD_TYPE` where needed.

Do you only have the mapping for the IMPORTED_LOCATION, or do you also need it for other `_<CONFIG>` properties?

**Comment by tronical** [comment]
> > If newer corrosion sets IMPORTED_LOCATION straight for a single-config generator then maybe we don't need the mapping anymore?
> 
> Corrosion [now](https://github.com/corrosion-rs/corrosion/pull/213/) _always_ sets `IMPORTED_LOCATION`, even for Multi Config Generators. Not setting `IMPORTED_LOCATION` caused a CMake developer warning, so I think the new behavior is correct.

Excellent. Agreed.

> Previously corrosion passed around the build config(s) as a function parameter, while now it just checks `CMAKE_CONFIGURATION_TYPES` and `CMAKE_BUILD_TYPE` where needed.
> 
> Do you only have the mapping for the IMPORTED_LOCATION, or do you also need it for other `_<CONFIG>` properties?

That's a good question. I don't think we have debug or release specific configs otherwise.

This makes me think that we can eliminate the entire mapping bits in SlintConfig.cmake. That should simplify the code and the currently failing test provides coverage for the scenario we're modifying.

I can push a change into your `update_corrision` branch if you'd like.

**Comment by jschwe** [comment]
Thanks for the help! It seems to work now. I force pushed because an earlier commit contained some accidentally commented code, that I didn't intend to commit. 
I also added a new commit which used `LIBRARY_OUTPUT_DIRECTORY` to let corrosion copy the dll. I'm not sure if this is tested in CI, but locally it seems to work on windows.

One thing you might want to verify is if there may be any issues with the `RPATH` on Linux/macos. I don't think this is new behaviour, but I recently discovered on macOS that the RPATH of an executable linking a rust shared library contains the absolute path of the `cargo/build` directory of corrosion and not the location where Corrosion copies the shared library to. I'm not really too familiar with dynamic linking, so I haven't looked deeper into it, but this could cause issues.

**Comment by tronical** [comment]
> Thanks for the help! It seems to work now. 

Yay! Thank you so much for your help!

>I force pushed because an earlier commit contained some accidentally commented code, that I didn't intend to commit.

That's perfectly fine :)

> I also added a new commit which used `LIBRARY_OUTPUT_DIRECTORY` to let corrosion copy the dll. I'm not sure if this is tested in CI, but locally it seems to work on windows.

Right, this isn't tested in the CI. I'm wondering about that. In #1025 we were initially tracking this.

I think that we might not want to code a value in `cpp/CMakeLists.txt` but respect whatever choice for example a user who uses `FetchContent` in Slint decides on. In the top-level `CMakeLists.txt` (not used with FetchContent), we set `CMAKE_RUNTIME_OUTPUT_DIRECTORY`. Ideally corrosion automatically respects that. We might also want to set `CMAKE_LIBRARY_OUTPUT_DIRECTORY` but perhaps to a `lib/` directory, since we don't need the `.lib` files on Windows or the `.so` symlink on Linux in `bin/` I think.

I might be missing something here though :)
 
> One thing you might want to verify is if there may be any issues with the `RPATH` on Linux/macos. I don't think this is new behaviour, but I recently discovered on macOS that the RPATH of an executable linking a rust shared library contains the absolute path of the `cargo/build` directory of corrosion and not the location where Corrosion copies the shared library to. I'm not really too familiar with dynamic linking, so I haven't looked deeper into it, but this could cause issues.

Yes, I think we had this issue in https://github.com/slint-ui/slint/pull/1069 and we ended up setting the  cmake `IMPORTED_NO_SONAME` property to avoid that absolute path entering the executable linking against the corrosion created library. Maybe one day this will be changed in cargo :)

**Comment by jschwe** [comment]
> In the top-level CMakeLists.txt (not used with FetchContent), we set CMAKE_RUNTIME_OUTPUT_DIRECTORY. Ideally corrosion automatically respects that.

Corrosion respects the `RUNTIME_OUTPUT_DIRECTORY` property (and the others) which is initialized by CMake to the value of `CMAKE_RUNTIME_OUTPUT_DIRECTORY`. So from the corrosion side this should work fine.

I did notice that `CMAKE_RUNTIME_OUTPUT_DIRECTORY` did not affect the .dll. The CMake documentation for [Runtime output artifacts](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#runtime-output-artifacts) says:

> A runtime output artifact of a buildsystem target may be:
> 
>   -  The executable file (e.g. .exe) of an executable target created by the [add_executable()](https://cmake.org/cmake/help/latest/command/add_executable.html#command:add_executable) command.
> 
>  -   On DLL platforms: the executable file (e.g. .dll) of a shared library target created by the [add_library()](https://cmake.org/cmake/help/latest/command/add_library.html#command:add_library) command with the SHARED option.

and for the [Library output artifacts](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#library-output-artifacts):

> A library output artifact of a buildsystem target may be:
>
>   - The loadable module file (e.g. .dll or .so) of a module library target created by the [add_library()](https://cmake.org/cmake/help/latest/command/add_library.html#command:add_library) command with the MODULE option.
> 
>  -  On non-DLL platforms: the shared library file (e.g. .so or .dylib) of a shared library target created by the [add_library()](https://cmake.org/cmake/help/latest/command/add_library.html#command:add_library) command with the SHARED option.

I'm not familiar with Windows, so I have no idea what the difference between an executable file .dll and a loadable module file .dll is, but it seems like your shared library is treated by CMake as the loadable module category. Maybe this observation already helps you pinpoint the issue?

> I think that we might not want to code a value in cpp/CMakeLists.txt but respect whatever choice for example a user who uses FetchContent in Slint decides on.

If FetchContent works similiar to add_subdirectory (as opposed to include), then the user would have to use the `CMAKE_XXX_OUTPUT_DIRECTORY` variables. Setting the target properties would not work, since Corrosion would have already evaluated the properties at that time. I tried deferring the evaluation until the end of the top-level CMake, but apparently CMake does not allow this (I don't remember what exactly the error was).

> Yes, I think we had this issue in https://github.com/slint-ui/slint/pull/1069 and we ended up setting the cmake IMPORTED_NO_SONAME property to avoid that absolute path entering the executable linking against the corrosion created library. Maybe one day this will be changed in cargo :)

Thanks, I'll have a look at the linked issue - maybe there is something Corrosion can do here.

**Comment by jschwe** [comment]
> I think that we might not want to code a value in cpp/CMakeLists.txt but respect whatever choice for example a user who uses FetchContent in Slint decides on.

I dropped that commit. I rebased the rest, updated to the final git tag and squashed.

**Comment by tronical** [comment]
> > I think that we might not want to code a value in cpp/CMakeLists.txt but respect whatever choice for example a user who uses FetchContent in Slint decides on.
> 
> I dropped that commit. I rebased the rest, updated to the final git tag and squashed.

Good idea, I can try to work on that separately. Thanks again so much!

**Review by tronical — APPROVED** [review]

**Pull request merged**
