### PR TITLE
Update winit

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Comment by ogoffart** [comment]
almost too easy

**Review by tronical — APPROVED** [review]

**Comment by ogoffart** [comment]
CI failure is strange. Maybe the binaries are now too big?

**Comment by tronical** [comment]
> CI failure is strange. Maybe the binaries are now too big?

It's also failing in master with the same error. We've had this a few days/weeks(?) ago, and then it went away again. It's quite weird that the error message from the linker is so... unhelpful.

**Comment by tronical** [comment]
I cleared the cache btw for the failed master build and that worked. Trying here as well.

**Pull request merged**
