### PR TITLE
Fluent polish

### PR DESCRIPTION
**Pull request by hunger**
Cosmetic change only: This makes the checkmark (CheckBox)/down-angle (ComboBox) a bit slimmer to match upstream style better.

### CODE REVIEW

**Comment by ogoffart** [comment]
could you attach a screenshot?

**Comment by hunger** [comment]
old, 
new

**Comment by ogoffart** [comment]
Yeah, the Old stuff is clearly a bug in the femto vg rendering.  
This is how the old svg looks like with the Qt backend:

Screenshot_20220407_121250

This is how it should look according to https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox

Screenshot_20220407_121529


So it looks like your change is fine.

That said, it's sad that femtovg has bugs and the bugs should probably be fixed.  But since it hasn't been fixed in all this time, it probably won't be fixed.

**Review by ogoffart — APPROVED** [review]

**Comment by hunger** [comment]
The old paths were more complex than the new ones, so this is a step into the right direction anyway:-)

**Comment by tronical** [comment]
Wonderful - that has been an eye sore :)

**Pull request merged**
