### PR TITLE
experiment for highlighting UX

### PR DESCRIPTION
**Pull request by szecket**
this ux works really well but ideally goes back to what was selected before right click OR the selection actually moves rather than the hover color

### CODE REVIEW

**Comment by szecket** [comment]
@hunger can you make it so rollover select reverts to whatever was selected originally if I don't left click on something in the list?

**Comment by hunger** [comment]
@szecket: I am trying to extend `PopupWindow` right now to make tat possible ;-)

**Comment by hunger** [comment]
I think i found a way around needing a new callback for the `PopupWindow` :-)

**Review by hunger — APPROVED** [review]
Let's get this merged if you are happy with my changes on top of yours.

**Comment by szecket** [comment]
I think it works well! How do you feel about it the interaction?

**Pull request merged**
