### PR TITLE
Simplify Rust Quickstart

### PR DESCRIPTION
**Pull request by tronical**
- Simplify quick start guide
- Remove substitution in vscode project quick pick

### CODE REVIEW

**Comment by ogoffart** [comment]
there are more reference to "cargo generate" in the repository (lib.rs / readme.md)

**Comment by tronical** [comment]
Oops, thanks, I'll fix those.

**Review by ogoffart — APPROVED** [review]
Note that there is an extra button on github "Use this template", maybe we can recommand preople that have a github account to do that in the docs (also valid for other languages)

**Comment by tronical** [comment]
I was wondering about the same. But OTOH it's an extra step that requires to be logged into GitHub I think (as the fork needs to be stored, as opposed to anonymously cloning from our repo).

**Pull request merged**
