### PR TITLE
Added Browser specific CSS prefixes to improve browser support

### PR DESCRIPTION
**Pull request by iodapson**
Added Browser specific CSS prefixes to improve browser support for older browsers. More support means uniform appearance/interface across browsers.

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks for the PR.
What browser in particular are you interested in supporting?
The online editor kind of need wasm to work, and I think all browser that supports wasm also support the unprefixed version.

**Comment by hunger** [comment]
We probably document a minimal supported browser version somewhere :-)

**Comment by ogoffart** [comment]
> We probably document a minimal supported browser version somewhere :-)

We don't :-/. Neither our website, nor our demos are tested with older browser than the onew we have on our desktop, which is the latest versions of the big browsers.

To be honest, I'd be fine with saying we only support one year old browsers

**Comment by iodapson** [comment]
Minimum Browser versions that support WebAssembly:
Chrome: 57^
Edge: 16^
Firefox: 52^
Opera: 44^
Safari: 11^

Can be verified here at [MDN](https://developer.mozilla.org/en-US/docs/WebAssembly) & [Caniuse](https://caniuse.com/wasm)

**Comment by iodapson** [comment]
Minimum Browser versions that support flexbox layout:
Chrome: 29^
Edge: 12^
Firefox: 28^
Opera: 17^
Safari: 9^

**Pull request closed without merging**
