### PR TITLE
feat: Add Key.Space to Key namespace.

### LINKED ISSUE #4303: Add Key.Space to Key namespace
Of course Key.Space can be substituted with " ", but I think it can make the code more readable.

### PR DESCRIPTION
**Pull request by trobanga**
Close #4303

### CODE REVIEW

**Comment by trobanga** [comment]
I tried to test the local version with a project of mine and overwrote the slint dep with:
```
[patch.crates-io]
slint = { path = "path/to/slint/api/rs/slint" }
```

But I get "  error: 'Space' is not a member of the namespace Key.

**Comment by tronical** [comment]
Where do you get that error? Do you use a `build.rs` by chance? You may have to adapt your `slint-build` dependency, too.

**Comment by trobanga** [comment]
I forgot to patch `slint-build`, too.
Thanks!

**Review by tronical — APPROVED** [review]
Great - thanks a lot!

**Pull request merged**
