### PR TITLE
Disallow callback overrides and duplicated callback declarations

### PR DESCRIPTION
**Pull request by tronical**
A duplicated callback would silently overwrite the previous declaration, which is counter-intuitive.

### CODE REVIEW

**Comment by tronical** [comment]
I was rather surprised that this is allowed. What do you think?

**Review by ogoffart — APPROVED** [review]

**Comment by ogoffart** [comment]
What bout things like 

```
TouchArea {
   callback clicked;
   callback width;
}
``` 

I think we handle that for properties.
We should also check for callback that there isn't a property with the same name, also in the parent.

**Review by ogoffart — CHANGES_REQUESTED** [review]
Yes, look a bit before when we emit the `Cannot override property` error.  We should actually do a proper lookup.

**Comment by tronical** [comment]
> What bout things like
> 
> ```
> TouchArea {
>    callback clicked;
>    callback width;
> }
> ```
> 
> I think we handle that for properties. We should also check for callback that there isn't a property with the same name, also in the parent.

That's allowed at the moment, and I guess we could continue to allow it. I was thinking that we could introduce a `super` qualifier (like `parent`) to give access to the "base" callback.

**Comment by tronical** [comment]
> Yes, look a bit before when we emit the `Cannot override property` error. We should actually do a proper lookup.

Ah, do you want me to change this PR to not only disallow duplicates but also disallow overrides?

**Comment by ogoffart** [comment]
> Ah, do you want me to change this PR to not only disallow duplicates but also disallow overrides?

Yes, i think the callback and property should obey the same overwriting rules.

**Review by ogoffart — APPROVED** [review]
A test with a property trying to override a callback and vice-versa would be nice.

**Comment by tronical** [comment]
> A test with a property trying to override a callback and vice-versa would be nice.

I'll take that part in a separate PR. This is just about callbacks not being able to override/duplicate themselves. Properties and callbacks with the same name can still co-exist (and have before this patch set).

**Comment by ogoffart** [comment]
> Properties and callbacks with the same name can still co-exist (and have before this patch set).

Ouch!  they shouldn't. that's a bug.

Currently, if you declare a property and a callback with the same name in the same component, the callback will simply replace the property and it's as if the property don't exist.

**Pull request merged**
