### PR TITLE
Rename `border-...-radius` to `...-border-radius`

### PR DESCRIPTION
**Pull request by ogoffart**
As per API review:
This is how you phrase it in english without dashes. It is consistent with `horizontal-alignment`.

### CODE REVIEW

**Comment by ogoffart** [comment]
fyi @jpnurmi

**Comment by jpnurmi** [comment]
Sounds fine. :+1: The original names proposed in #157 apparently came from CSS.

**Comment by ogoffart** [comment]
Ah, I had forgotten this came from CSS.  In light of that, it seems like it might be better to keep it as is (`border-top-left-radius`, ...) for consistency with CSS

@tronical: do you agree?

**Comment by tronical** [comment]
ACK, `border-*-radius` are still good names. I'm fine with staying with what we have.

**Pull request closed without merging**
