### PR TITLE
Implement -L flag for the LSP tool, similar to the viewer

### LINKED ISSUE #5144: Support libraries in LSP
Slint's LSP tool should support `@library`-style imports, like the viewer already does though `-L`.

If there isn't anything blocking this (which there doesn't seem to be, I've already looked into it), I will submit a PR.

### PR DESCRIPTION
**Pull request by Tmpod**
You can pass `-L foo=/path/to/foo` to add `@foo` as a library when starting the LSP server.

The change was pretty much just lifted from the viewer tool. I tested this in a real project with a real library.

Closes #5144

### CODE REVIEW

**Comment by Tmpod** [comment]
That failed docs check seems to be related to a misconfiguration of reviewdog?

**Review by ogoffart — APPROVED** [review]
Thanks for your patch! Looks good to me.

The failure in the docs CI is because you need to run `cargo fmt` to format the change. Could you please do that?  (But indeed, reviewdog was unable to post a nice comment about it because a configuration problem)

**Comment by Tmpod** [comment]
Ah I see, will fix in a sec!

**Comment by ogoffart** [comment]
thanks a lot!

**Pull request merged**
