### PR TITLE
UX enhance the Printerdemo primary screen

### PR DESCRIPTION
**Pull request by NigelBreslaw**
- The general page change animation is more subtle. It's now a combo of fade in and move. As opposed to a full page slide.
- Fixes the position of the sidebar selection SVG to remove a broken curve.
- The SVG also has been tweaked to make it symmetrical and remove the lopsided bulge it had. 
- The sidebar buttons touch area covers the whole space they represent, as opposed to just being the same size as the icon.
- The code has been simplified a bit. Layout values are moved to DemoPalette and animation values are based on reusable variables to make changing the timings easier.

### CODE REVIEW

**Comment by ogoffart** [comment]
I tried this PR and i see two problems:

 - There seem to be a pixel gap between the "rounded tab" and the page (that wasn't the case before)
 - The touch on the main area doesn't work well anymore, i don't explain it, but opening the printing queue item doesn't work always and also you cant go back from page anymore. Maybe some touch area are covering a much too big area?


image

**Comment by NigelBreslaw** [comment]
Fixes are in. I don't see the pixel gap on my HiDPI MacBook screen. I need to grab a SD monitor to see if some of these things show there. But regardless the expression should have simply used the width of the image and not be using magic numbers. Should be fixed, but right now I cannot test on non HiDPI.

**Comment by ogoffart** [comment]
Thanks, the interaction seems to be fixed, but the gap between the tab is still there.
It does indeed depend on the scale factor (which you can change with an environment variable)
`SLINT_SCALE_FACTOR=1` or `SLINT_SCALE_FACTOR=2` doesn't reproduce the gap, but `SLINT_SCALE_FACTOR=1.5` (my default value) reproduces the gap.

**Comment by NigelBreslaw** [comment]
Okay well this solves the mystery of why the SVG has a smooth curve, but in the original demo it isn't. It was shifted over by a pixel to remove the gap. Could this be a bug in slint with SVG files? At least when I open the svg in Affinity Designer there is no gap at the right edge. Seems a valid file. 

I've attached a pic showing the issue that I wanted to fix, but for now will just leave in the demo. Designers love to have smooth curves.
image

**Review by ogoffart — APPROVED** [review]
Cool. Please squash the commits

**Pull request merged**
