### PR TITLE
Allow scrolling through tabs for all backends

### LINKED ISSUE #5002: Allow user to scroll through the tabs using the mouse wheel for Qt backend
**Steps to reproduce**
The issue can be reproduced on Linux using the example gallery application.

1. `git clone https://github.com/slint-ui/slint`
2. `cd examples/gallery`
3.  `cargo run`

**Expected behavior**
When hovering over the tab, it should be possible to scroll through the tabs using the scroll wheel.

**Actual behavior**
Switching tabs of the tab widgets using the scroll wheel is not possible.

**Platform**
Fedora Linux 40, Rust, Qt Backend, Wayland

### PR DESCRIPTION
**Pull request by notfirefox**
**Changes**
- Introduce `TabBarBase` that implements scrolling through tabs functionality
- Update `TabBarImpl` for all styles to inherit from `TabBarBase`

Closes #5002

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks for the patch.

The `consistent_styles` test is failing. Normally this test checks that all the style have the same API. But TabBarImpl is an internal component that actually should be ignored in 
https://github.com/slint-ui/slint/blob/5a36de73c6ebdb6359cb3a7b3cd067fda9da2493/internal/compiler/tests/consistent_styles.rs#L150-L151
But the alternative would be to have the TouchArea as a children instead of inheriting from it.

In fact, I think we probably should have this behavior with every style.
We could have a TabBarImplBase in internal/compiler/widgets/common to share the logic across all styles.

Note: no need to open issues before making a PR.

**Comment by notfirefox** [comment]
I tried implementing this feature without letting TabBarImpl inherit from TouchArea first, but I couldn't get it to work.
Either the component would not respond to clicks anymore or the keyboard actions (switching between tabs using the left and right arrow keys) wouldn't work anymore.

I will try abstracting things away into a dedicated TabBarBase component. I think it will mostly contain the switching tabs functionality (through arrow keys and through the mouse wheel).

**Comment by notfirefox** [comment]
This does not appear to work at all for me?
```slint
i-focus-scope := FocusScope {
    property <int> focused-tab: 0;

    x: 0;
    width: 0; // Do not react on clicks

    key-pressed(event) => {
        if (event.text == "\n") {
             root.current = root.current-focused;
             return accept;
        }
        if (event.text == Key.LeftArrow) {
             self.focused-tab = Math.max(self.focused-tab - 1,  0);
             return accept;
        }
        if (event.text == Key.RightArrow) {
             self.focused-tab = Math.min(self.focused-tab + 1, root.num-tabs - 1);
             return accept;
        }
        return reject;
    }

    key-released(event) => {
        if (event.text == " ") {
             root.current = root.current-focused;
             return accept;
        }
        return reject;
    }
}
```
 This is from the `tabwidget.slint` file of the material style. The other styles (except for qt - that one is different) seem to have a similar implementation. I tested this both on the master branch and on my new branch and in both cases I could not get the functionality to work. The qt implementation seems to work as expected though.

**Review by ogoffart — APPROVED** [review]
Thanks a lot! Looks good to me.
Added @FloVanGH as a reviewer since that touches all the styles.


I notice that you formatted the files with the LSP. We usually don't do that because it formats a lot of stuff not so great right now. But it this case it seems Ok.

What would be super is if this behavior could be tested with a tests in `tests/cases/widgets/` the tests in this directory are run for every style. (see the combobox.slint one for example) We only started testing the widgets. There could be a tests/cases/widgets/tabwidget.slint that tests the key shortcut and the mouse wheel.
(See tests/cases/input/scroll-event.slint for an example on how to send a scroll event). (But this is just for extra points, the PR is already good as it is)

**Pull request merged**
