### PR TITLE
Add slint logo to settings page

### PR DESCRIPTION
**Pull request by hunger**
This is what this looks like:

image

### CODE REVIEW

**Comment by ogoffart** [comment]
The screenshot seems to be taken with the slint viewer.  But that does smooth scaling, while this is not implemented with the software renderer.

You can see the result with the software renderer using the simulator:
```
SLINT_STYLE=fluent WINIT_X11_SCALE_FACTOR=1 cargo run -p printerdemo_mcu --no-default-features --features=mcu-simulator
```

**Comment by hunger** [comment]
You are right, that does not look good with the software renderer at all:-(

I pre-scaled smaller logo now and use that instead.

**Comment by ogoffart** [comment]
I'm hesitant adding more images to the logo directory as they stay there forever.
I'd put it in the printerdemo_mcu folder to not pollute stuff
Maybe use logo/slint-logo-simple-light.svg (or logo/slint-logo-simple-dark.svg depanding of darkmode ?) 

I wonder if we could use the SVG directly and have the compiler render the right size if it is hardcoded. (in embed_image.rs:284, we could query the property binding on width and height and try to see if it is a NumberLiteral)  But i guess that's a bit too much to ask for now.

**Comment by hunger** [comment]
> I'm hesitant adding more images to the logo directory as they stay there forever. I'd put it in the printerdemo_mcu folder to not pollute stuff

We will pollute the tree one way or the other: If we put them into printerdemo_mcu, then we will end up copying that file to other places and litter the tree that way...

> Maybe use logo/slint-logo-simple-light.svg (or logo/slint-logo-simple-dark.svg depanding of darkmode ?)

I was thinking the same, but was afraid that would needlessly increase the size of the binary and litter the tree even more with one additional logo file.
 
> I wonder if we could use the SVG directly and have the compiler render the right size if it is hardcoded.

Having the compiler do the magic of rendering SVG nicely would be seriously cool! Ideally we should not have SVGs on the divice and pre-render them all (maybe with a heuristic to not pre-render SVGs used in several sizes?).

**Comment by hunger** [comment]
NEW AND IMPROVED!

With light and dark icons, both of them living in the ui directory of printerdemo_mcu. Switching between the two is also implemented.

**Comment by ogoffart** [comment]
Looks good!

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
