### PR TITLE
Try to improve rendering (positioning) of signed field distance font.

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Review by tronical — APPROVED** [review]

**Comment by ogoffart** [comment]
Updated. This time it is hopefully correct aligned. (at least it looks better now)

**Review by tronical — APPROVED** [review]
Great :).

**Comment by ogoffart** [comment]
screenshots had to be re-generated as the advance is now rounded instead of truncated, also without distance field.  I think it looks a bit better.

**Review by tronical — APPROVED** [review]
Yes, makes sense to round the advance. Also looks better.

**Pull request merged**
