### PR TITLE
Move the Skia renderer into a separate crate

### PR DESCRIPTION
**Pull request by tronical**
The crate is an internal crate until the API has been polished and documented, after which we can call slint-renderer-skia for example.

This also duplicates a little bit of the glutin setup code, because that would otherwise have to go into another shared crate.

### CODE REVIEW

**Comment by tronical** [comment]
Force push was just a one-liner typo causing the win32 build to fail in `opengl_surface.rs`.

**Comment by ogoffart** [comment]
Some documentation is missing.

I think it should at least have a README and a crate documentation (see other internal crates)
some amount of documentation for public items would be nice.

**Review by ogoffart — APPROVED** [review]

**Comment by ogoffart** [comment]
Need not to forget to add it in the scripts/publish.sh

**Comment by tronical** [comment]
Thanks - done :)

**Pull request merged**
