### PR TITLE
TextInput: Add undo/redo support

### PR DESCRIPTION
**Pull request by Waqar144**
#474

### CODE REVIEW

**Review by tronical — COMMENTED** [review]
Great :). I think that's a reasonable data structure and approach for our string based TextInput. Thanks a lot!

From what I can see, there are issue left:

Due to our C++ bindings, the fields in `TextInput` need to be `repr(C)` for cbindgen. I think `Vec` is the issue here, but that could become a `SharedVector`.

Another option would be to keep it as a Vec and use a `TextInputDataBox` that's heap allocated, like with `FlickableDataBox`.

Olivier, do you have any preferences here?

**Comment by ogoffart** [comment]
> Olivier, do you have any preferences here?

I prefer using SharedVector

**Comment by tronical** [comment]
@Waqar144 Would you like me to take over to take care of the binding bits, or would you like to give it a try?

**Comment by Waqar144** [comment]
I had to change things quite a bit to make it work:
- added a `pop()` method to `SharedVector`
- `UndoItem` is now a struct with a `UndoItemKind` field, previously it was an `enum`. I had to change it because the old struct was non-trivial

**Review by tronical — APPROVED** [review]
Looks good to me - thanks!

**Pull request merged**
