### PR TITLE
Added Tetris made with slint

### PR DESCRIPTION
**Pull request by GaspardCulis**
I added a new project of mine (Tetris) to the "Made with Slint" section

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks!

By the way, the repository doesn't contain a license, you probably should fix that.

**Comment by tronical** [comment]
The code and design looks great! Any plans to do a wasm version for online playing? Could use GitHub pages. (I can also try to help if that's interesting for you)

**Comment by GaspardCulis** [comment]
> The code and design looks great! Any plans to do a wasm version for online playing? Could use GitHub pages. (I can also try to help if that's interesting for you)

I'll try to do that, would be a plus to showcase the capabilities of Slint, I'll submit a new PR when it's done 👍

**Comment by tronical** [comment]
I think the js, wasm, and html file(s) need to be served from the same domain.

It might be easiest to do the GitHub pages setup where you push all the files (html, js, and wasm) into either a separate repo or a branch in your existing repo (often called gh-pages) and then go to the repository settings and select that branch to be the one to serve GitHub pages from.

**Pull request merged**
