### PR TITLE
Pass a larger scale as dpi to make texts clearer.

### LINKED ISSUE #2615: Femtovg is blurry with low DPI
Issue #1362 suggests using skia instead, but I'd like to discuss the reason of the blurry text.

https://github.com/slint-ui/slint/blob/3657c63c8ec4bfdb95821d5bd1f6f8f5d42f45d8/internal/renderers/femtovg/lib.rs#L137-L140

Here we pass DPI=1.0 to femtovg. The reason is fair that we handle the DPI ourselves. But femtovg also uses the DPI value for anti-alias.

https://github.com/femtovg/femtovg/blob/7ac3df83e92966243c6c0c648cdd989682e14072/src/lib.rs#L368-L371

I think it is necessary to pass the right DPI to make the text less blurry.

### PR DESCRIPTION
**Pull request by Berrysoft**
Fixes #2615 

I still don't understand all the code in the renderer, but it works now:)

### CODE REVIEW

**Comment by tronical** [comment]
Nice discovery! This might indeed be a good way to improve quality. I need to take a look at this next week, unless somebody beats me to it. My guts feeling is that perhaps it would be easier to add api to femtovg to just tweak the thresholds but keep the metrics calculations as-is. What do you think?

**Comment by Berrysoft** [comment]
Maybe it's a better solution, but I need much more time to do that...

**Comment by Berrysoft** [comment]
I opened an issue in `femtovg` repo: https://github.com/femtovg/femtovg/issues/160

However, it may take a long time to update the upstream dependency. I suggest taking this temporary fix at first.

**Comment by Berrysoft** [comment]
@tronical I investigated further and couldn't find the root cause of the problem. However, the only related parameter that makes texts clearer, is the DPI itself, not some anti-alias tolerance. Therefore, this PR is the only fix I could find out.

**Comment by Berrysoft** [comment]
@tronical ping? How do you think about this PR? Blurry texts are found on both Windows and Linux. Not found on mac because the dpi of macbook is very large:) It is not a severe problem, but it gives bad user experiences.

**Comment by tronical** [comment]
Hi! Thanks for your patience :). I had another look and I think that you're right. What you're proposing makes sense.

So from what I understand we pass the scale factor to FemtoVG and from that point on we feed logical coordinates into FemtoVG and we get physical metrics out, _plus_ improved visual quality (that's the key here).

I think that this requires a few changes to his PR though:

1) I think in the [`Font`](https://github.com/slint-ui/slint/blob/fcfa1da5bc4ae7ff7217ea115eff593b7a9cdae0/internal/renderers/femtovg/fonts.rs#L80) data structure, we need to store the pixel size as logical length.
2) Functions like [`init_paint`](https://github.com/slint-ui/slint/blob/fcfa1da5bc4ae7ff7217ea115eff593b7a9cdae0/internal/renderers/femtovg/fonts.rs#LL87C10-L87C10) need to also take a `LogicalLength` for the letter spacing.
3) Everywhere afterwards in the code we currently assume that metrics coming out of FemtoVG are physical pixels, which remains true as far as I can see. That means that in your change where you divide the font_height by the scale factor is not needed anymore.

Does that make sense? Would you feel comfortable making these changes? :) (it's okay if not, I can give it a try next week perhaps)

**Comment by Berrysoft** [comment]
I'm now a little confused about the phenomenon passing the dpi value to femtovg. For a monitor that is 1.25x scaled, the best value to pass to femtovg is 2. That's why I add `.ceil()` to the scale factor.

**Comment by tronical** [comment]
Hm, but if we do that, then all computed text metrics will assume a monitor scale factor of 2, instead of the real 1.25x. That doesn't seem quite right either.

**Comment by tronical** [comment]
But then that would have to be done to all metrics reported by FemtoVG (glyph advances, etc.). I'm starting to think that perhaps just adjusting the threshold for rendering in FemtoVG may be easier. What was the problem with that again?

**Comment by tronical** [comment]
Or could it be that what you see is that text appears sharper because it's rendered _bigger_? (which it shouldn't be)

**Comment by Berrysoft** [comment]
Well, the text appears sharper because the dpi passed to femtovg is larger, but the text itself is still the *right* size. The anti-alias threshold will *not* influence the text.

**Comment by tronical** [comment]
You're right (Again :-). I see now why this doesn't change the text metrics: We're calling `measure_font`, etc. on the `TextContext`, which is _not_ bound to the `Canvas` and thus doesn't use the `device_px_ratio`. There's only one place where we call a metrics related function on the `Canvas` and where `device_px_ratio` comes in: The `measure_font` call, the result of which you (correctly) divided out the scale factor again.

However: When the text is _rendered_, we call `Canvas::fill_text`, and that function will scale the glyphs not only by the current transform set on the canvas (that's fine), but it will also include the `device_px_ratio`:

From femtovg's `fill_text`:
```rust
        let scale = self.font_scale() * self.device_px_ratio;
        let invscale = 1.0 / scale;

        let mut stroke = paint.stroke.clone();
        stroke.line_width *= scale;

        let mut text_settings = paint.text.clone();
        text_settings.font_size *= scale;  // <-- here font_size is made bigger than what it was when laying out the text
        text_settings.letter_spacing *= scale; // <-- here the letter spacing is increased beyond what it was when laying out the text

        let mut layout = text::shape(
            x * scale,
            y * scale,
            &mut self.text_context.borrow_mut(),
            &text_settings,
            text,
            None,
        )?;
```

That means the dpi argument to `set_size` will not only affect the text rendering quality, but it will also affect the positioning and size of the glyphs as rendered (not as laid out). I'll try to make a screenshot with a ruler to see if the difference is visible :)

**Comment by tronical** [comment]
I stand correct again, I see that in femtovg the glyphs are laid out in the higher resolution, but last minute in `render_direct` as well as when drawing the quads for rendering from the glyph atlas, the `device_pixel_ratio` is divided out again.

I have a bit of a weird feeling about this, and it's somewhat tricky: We must still do the text layout that we do without the device_px_ratio applied.

So let's take your patch, but I'd like to ask you to make one change to it: Instead of adjusting the `font_height` variable, because it is computed on the `Canvas` where the `device_pxel_ratio` is applied, please change the code with this patch to compute the height from the unscaled font instead. That way the division by the scale factor is not needed anymore:

```patch
diff --git a/internal/renderers/femtovg/fonts.rs b/internal/renderers/femtovg/fonts.rs
index 2d368baf8..e2959257b 100644
--- a/internal/renderers/femtovg/fonts.rs
+++ b/internal/renderers/femtovg/fonts.rs
@@ -133,6 +133,14 @@ pub fn text_size(
         }
         euclid::size2(width, lines as f32 * font_metrics.height())
     }
+
+    pub fn height(&self) -> PhysicalLength {
+        let mut paint = femtovg::Paint::default();
+        // These are the only two properties measure_font() needs
+        paint.set_font(&self.fonts);
+        paint.set_font_size(self.pixel_size.get());
+        PhysicalLength::new(self.text_context.measure_font(&paint).unwrap().height())
+    }
 }

 pub(crate) fn text_size(
diff --git a/internal/renderers/femtovg/itemrenderer.rs b/internal/renderers/femtovg/itemrenderer.rs
index fa0e70bfb..77958eb8d 100644
--- a/internal/renderers/femtovg/itemrenderer.rs
+++ b/internal/renderers/femtovg/itemrenderer.rs
@@ -398,7 +398,7 @@ fn draw_text_input(
             };

         let mut canvas = self.canvas.borrow_mut();
-        let font_height = PhysicalLength::new(canvas.measure_font(&paint).unwrap().height());
+        let font_height = font.height();
         let text: SharedString = visual_representation.text.into();

         let mut cursor_point: Option<PhysicalPoint> = None;
```

Does that make sense to you? Or would you like me to do the change on top of yours?

**Comment by Berrysoft** [comment]
I applied your patch and removed the division. The conflicts are solved. I'm sure the font measurement works well on my machine. Now waiting for CI:)

**Review by tronical — APPROVED** [review]
Thanks for the quick response. If the CI is green (good chances :), I'll squash and merge it, ok?

**Comment by Berrysoft** [comment]
Ok, now it's green:)

**Comment by tronical** [comment]
> This branch cannot be rebased due to conflicts

Could you rebase your branch, or shall I try to do it?

**Comment by Berrysoft** [comment]
Maybe you need to refresh the page. I see "This branch has no conflicts with the base branch" now.

**Comment by tronical** [comment]
I still see this after refreshing the page.

**Comment by tronical** [comment]
Ah, I can still squash it. Alright.

**Pull request merged**
