### PR TITLE
Reject key-events on disabled FocusScope.

### PR DESCRIPTION
**Pull request by FloVanGH**

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]
thanks

**Review by ogoffart — COMMENTED** [review]
Actually, the documentation of the enabled property states the current behavior.
It was documented and added the failling test to reflect the behavior at the time in https://github.com/slint-ui/slint/pull/2530 There is some discussion there, and it resulted in the issue  https://github.com/slint-ui/slint/issues/2535

I think we should go for the change even if it is a breaking change. a disabled FocusScope should not accept input.
@tronical : agree?

(and https://github.com/slint-ui/slint/issues/2535 can be closed)

**Comment by FloVanGH** [comment]
@ogoffart ok then I will wait for the response of @tronical before completing this PR.

**Comment by FloVanGH** [comment]
I close this now because we've discussed an alternative solution that should fix also the origin bug of keyboard interaction on a disabled ComboBox, that not yet breaks the current behavior of FocusScope.

**Pull request closed without merging**
