### PR TITLE
Add a dark theme for the fluent style

### PR DESCRIPTION
**Pull request by tronical**
This is computed via the fluent theme designer by swapping text and background.

image

### CODE REVIEW

**Comment by tronical** [comment]
I couldn't quite find "the official" theme but many people making their own. The Fluent UI Theme Designer seemed like the easiest way to map existing palette and introduce a dark mode. It's telling though that the actual widgets aren't using all palette entries.

**Comment by tronical** [comment]
Alternatively I need to understand what https://docs.microsoft.com/en-us/fluent-ui/web-components/getting-started/styling#light-and-dark-mode would do.

**Comment by ogoffart** [comment]
Nice.

Im concerned that this may break applications that did
````
Text { color: black; }
````

Or something similar with images or path or so.

Although the native style had the problem already then.

Perhaps this should be opt in somehow? Or we just do it anyway.

**Comment by tronical** [comment]
I'm tweaking this further. A darker shader for "white" and lightening up the neutralLight shades gives a nice contrast for the button. This is also a good reference https://github.com/microsoft/fluentui/issues/9795#issuecomment-511586994

**Comment by tronical** [comment]
> Although the native style had the problem already then.
>
> Perhaps this should be opt in somehow? Or we just do it anyway.

Yeah, I think we should do it anyway for now and tackle the customisation part separately.

**Comment by tronical** [comment]
Bonus: Also made a fix for the AboutSlint logo

**Comment by tronical** [comment]
This crashes because the `NativeStyleMetrics` are now used and instantiated from multiple testing threads. We need to move the dark mode detection into corelib.

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
