### PR TITLE
Updated BackendSelector API

### PR DESCRIPTION
**Pull request by tronical**
Based on API review.

### CODE REVIEW

**Comment by tronical** [comment]
Still marked as draft to also see CI issues.

**Comment by tronical** [comment]
There might be CI issues left, but I think the API is ready for review now.

**Review by ogoffart — COMMENTED** [review]
Should we `select()` on `Drop` ? 
I fear that a missing call to select is going to be an unnoticed problem.

**Comment by tronical** [comment]
We could. I mean, select on drop if select wasn’t called earlier? And panic if there is an error?

So use would be either:
- end call with select() and possibly handle error
- don’t call select() but implicitly select on drop and panic on error

Is that correct?

**Comment by ogoffart** [comment]
My concern is that someone can do something like:

```rs
let _selector = BackendSelector::new().require_opengl_es_with_version(3, 0);
```

And nothing would happen.

That said, the use of `_` could be a hint that something isn't right. Yet, it feels dangerous.


> We could. I mean, select on drop if select wasn’t called earlier? And panic if there is an error?

Yes, that's what I mean.

**Comment by tronical** [comment]
> > We could. I mean, select on drop if select wasn’t called earlier? And panic if there is an error?
> 
> Yes, that's what I mean.

Sounds good to me. I'll do that.

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
