### PR TITLE
Node.js: Run tests with tracing enabled

### PR DESCRIPTION
**Pull request by tronical**
Occasionally the tests fail mysteriously on Linux in the CI. This is an attempt to diagnose.

### CODE REVIEW

**Comment by ogoffart** [comment]
I'm currious what kind of failure you're trying to diagnose.

Most faillure i've seen are:
```
 /home/runner/work/slint/slint/api/node/index.js:470
            let instance = definition.create();
                                      ^

Error: Could not initialize backend.
Error from Winit backend: Error initializing winit event loop: the requested operation is not supported by Winit
```

Are you thinking that enabling tracing will show some logs from winit?

**Comment by tronical** [comment]
Yes. At least on macOS I get a decent amount of output from winit that comes through the log crate. I've used that once to debug something, and I thought maybe it'll help us here, too. Not sure yet either how beneficial, but it's either that or a patch winit crate that adds debug output at the place where I think the error happens (but I don't see how it can fail..).

**Comment by tronical** [comment]
This doesn't seem to help diagnose the issue. We discussed and I'll change this to use the testing backend along with a fix to patch the testing dependency out before uploading to npm.

**Comment by tronical** [comment]
Replaced by #5064

**Pull request closed without merging**
