### PR TITLE
online_editor: zoom preview

### PR DESCRIPTION
**Pull request by hunger**
Zoom level controls

### CODE REVIEW

**Comment by tronical** [comment]
I tried this change locally and for me now the preview area is empty after startup. Only after pressing "+" or "-" once, the hello world shows up.

**Comment by tronical** [comment]
Controls wise I think a slide works better than a spin box, but otherwise I think this makes sense.

I think implementation wise the pixel scaling is wrong though - we should scale with Slint's scale factor and not scale the bitmap. But that could be done in a separate change.

Interaction wise, I think zooming should also work like in figma - with a shortcut. For me that's Command + wheel and Command + wheel press to pan. This could be done separately as well, of course.

What do you think?

**Comment by ogoffart** [comment]
I think the zoom control as iseen on the screenshot are taking precious space for the preview. Not everyone has a 8k screen 😂.

Maybe the zoom level should be placed in the toolbar?

I'm wondering if this is really a feature we want to do right now though. I think more important would be a way to resize the preview.
Eg: The canvas should take the full size of the preview tab by default, unless constraint otherwise. Or there should be other way to resize like one resize a window.  And I think this is more important than a zoom level and that the zoom feature might make it more complicated.

**Comment by tronical** [comment]
> I tried this change locally and for me now the preview area is empty after startup. Only after pressing "+" or "-" once, the hello world shows up.

As the change was merged despite this comment, I've filed https://github.com/slint-ui/slint/issues/1945 as follow-up for tracking. Since me and Florian are the only folks with access to Safari, I would have preferred debugging the issue as part of this PR.

**Pull request merged**
