### PR TITLE
vscode: Apply biome fixes

### PR DESCRIPTION
**Pull request by hunger**
No manual change in this PR at all, just the result of `npm run lint:fix`.

### CODE REVIEW

**Comment by NigelBreslaw** [comment]
What is your view on the rule that tries to use 'const' on items that don't change over 'let'? I noticed a ton of code in api/node is written in the style of using 'let' for everything. So this rule will result in a ton of code changes. In JS 'const' is close to meaningless as you can still mutate arrays, objects, maps, etc. It's just a sort of vague hint that if you see 'let' you should expect to see code directly changing this item somewhere else. 

Personally I lean towards us just going with the default rules. They are pretty thin and sort of industry standard. But also I have no interest in arguing for or against const vs let because its not a real discussion due to JS not having what real coders expect 'const' to mean.

**Comment by hunger** [comment]
I like hints, even when vague...

**Comment by tronical** [comment]
Data point: I agree that `const` is useless in JS. I find it easier to stick with `let` as that's already in my fingers from Rust :) (despite different semantics).

**Comment by tronical** [comment]
> @tronical What editor do you use. The flip side is once we turn this on you will get red squiggles as you type. Also you can use let to your heart content and then afterwards use the auto fix :D

I'm using VS code.

**Pull request merged**
