### PR TITLE
Just for quick feedback for keyboard modifier handling

### PR DESCRIPTION
**Pull request by lukas-jung**
This is not final at all the `move_cursor_by_word()` is more or less a copy with duplication of `move_cursor` etc.
I just need some quick feedback about the `SemanticModifier` part.
@tronical: you didn't like that when I wanted to add it to `KeyboardModifiers`.

But I think some sort of abstraction like that is good. Actually there already exists the `AnchorMode`, which serves a similar purpose, but it needs a struct and a From implementation for every semantic/mode.

If you are ok with my approach, I would also replace the `AnchorMode` with the `SemanticModifier`, by adding a `KeepAnchor` to it.

Of course if you have an idea for a better abstraction, I wanna hear about it.

### CODE REVIEW

**Comment by tronical** [comment]
I think it's good to have an abstraction, but I think that it should be on the level of the entire key event, because it isn't just control vs. meta vs. alt.

For example to navigate to the line below the cursor, you can press the down arrow on macOS, but you can also type [Control-N](https://support.apple.com/en-us/HT201236#text).

In the `TextInput`'s `key_event` implementation I think there should be one call like this 

```rust
match event.standard_shortcut() {
    Some(StandardShortcut::MoveToNextLine) => { ... },
    ... 
}
```

`standard_shortcut()` could be provided by trait (or directly in the impl?) and return an `Option` of an enum that has the standard shortcuts we want to support.

It is in the above function where the match for arrow down should be done for all platforms, and when on macOS (or iPadOS, or iOS) it should also look for Command-N. That way we can centralise the table for platform specific standard shortcuts in one place and keep the code in `TextInput` on the semantic level.

We could also, in theory, let the backend provide this entirely. So Qt would map from `QKeySequence::StandardKey` and we'd have a self-baked table in the GL backend. But I'm not sure it is worth the trouble.

@ogoffart @hunger what do you think?

**Comment by lukas-jung** [comment]
I like that idea. But since it is a bit more complicated i'd prefer to do that in a separate PR and use my simple approach for this one. Perhaps we can create a `text_shortcut()` in `text.rs` and a `common_shortcut()` in `KeyEvent`?

Also for a lot of mac shortcuts we should disable the cmd -> ctrl mapping.

**Comment by hunger** [comment]
I think it would scale better if we defined logical keys for important operations we want to cover. The widgets then only need to work in terms of these special keys and the backends are free to generate those in whichever way makes most sense for the environment they target.

That way we do not need to pool knowledge of all the different platforms and their peculiarities into one place in the widget layer.

**Comment by tronical** [comment]
>  like that idea. But since it is a bit more complicated i'd prefer to do that in a separate PR and use my simple approach for this one.

Sure :)

> Also for a lot of mac shortcuts we should disable the cmd -> ctrl mapping.

Can you elaborate what you mean with disabling?

**Comment by lukas-jung** [comment]
> Can you elaborate what you mean with disabling?

right now the command key sets the ctrl flag in KeyModifiers.
I don't know were this is done though.
And I think we shouldn't do that anymore if we have proper shortcut handling.

**Comment by tronical** [comment]
> right now the command key sets the ctrl flag in KeyModifiers.

Yes.

> I don't know were this is done though.

In the GL backend it's done here: https://github.com/slint-ui/slint/blob/6622f33327a49568a8c361f9b213e59cc8af31b5/internal/backends/gl/event_loop.rs#L452
And for the Qt backend this is done inside Qt: See the note at the end of https://doc.qt.io/qt-5/qkeysequence.html#details .

> And I think we shouldn't do that anymore if we have proper shortcut handling.

I think the behavior that Qt provides and that we mirror in the GL backend is sensible, and from my own experience with Qt it has worked rather well. I think the behavior makes sense and makes it easier to write cross-platform code without compromising on the ability to write macOS specific code. What are the arguments in favour of reverting the behavior?

**Comment by hunger** [comment]
This mapping is in backends/gl/event_loop.rs. Look for "ModifiersChanged" event.

Note that winit was in the process to revamp their entire event handling then I talked to them a month ago or so, so they may change that in their next biggish version bump.

**Comment by lukas-jung** [comment]
> I think the behavior that Qt provides and that we mirror in the GL backend is sensible, and from my own experience with Qt it has worked rather well. I think the behavior makes sense and makes it easier to write cross-platform code without compromising on the ability to write macOS specific code. What are the arguments in favour of reverting the behavior?

Well control isn't command. It is a hack and it no longer needed when we have a central Shortcut to Semantic translation and interpretation in event.

- If we implement the Shortcuts form the apple website we always have to change cmd and ctrl.
- if we implement control clicking for context menu with one button mouses we have to make it command clicking. 
- if at some point this becomes a public API and someone needs a terminal emulator, they have to use cmd for control sequences etc.

The idea behind my SemanticModifier::StandardShortcut was to map ctrl(windows and linux) and cmd(mac) to it.
So that we do this on a semantic level. but I don't consider low level meddling with modifiers as very elegant.
At least not longterm when this becomes a public api. (I guess this needs to happen at some point)

**Comment by tronical** [comment]
> Well control isn't command. It is a hack and it no longer needed when we have a central Shortcut to Semantic translation and interpretation in event.

What about applications that are not interested in standard shortcuts? Applications can have their own domain specific shortcuts. Evidently typically shortcuts on macOS start with "command" (as opposed to control), while on the other platforms they start with "control".

So either we map command to control on macOS and control to meta, and applications can just use "control" for their own shortcuts, or they have to have "#ifdefs" in their .slint/rust/c++ code to apply the mapping that we are applying at the moment (and that Qt has for literally decades). 

> If we implement the Shortcuts form the apple website we always have to change cmd and ctrl.

I think "always" is "once".

**Comment by lukas-jung** [comment]
> So either we map command to control on macOS and control to meta, and applications can just use "control" for their own shortcuts, or they have to have "#ifdefs" in their .slint/rust/c++ code to apply the mapping that we are applying at the moment (and that Qt has for literally decades).

Of course there needs to be some mapping. What I'm saying is that we leave the actual modifiers as they are and add something else to do that.

The simplest approach would be a getter `short()` in `KeyboardModifiers` that returns control on windows and meta on mac.
This can be used for all shortcuts that are shared between all operating systems.
This way we can still get the original keys that were actually pressed were we want them.

**Comment by tronical** [comment]
> Of course there needs to be some mapping. What I'm saying is that we leave the actual modifiers as they are and add something else to do that.

Yes, true, we can do that. I think that should be a separate change. The current behavior of mapping command to control is documented in the public Slint API, so changing it is an API breaking change that requires a new major Slint version and documentation how users can adapt change their application code. We can discuss how to do that, but I think it's not in the same scope as adding support for more standard shortcuts in `TextInput`.

**Comment by lukas-jung** [comment]
Yes it is definitely not part of the Shortcut handling.
If I seam a bit pedantic and stubborn about the whole thing, it is of my point of view about the control key:
for me that is the control sequence key that was misused by the windows developers as the shortcut key, which leads to weird copy shortcuts in the windows terminal. This switching of the buttons leads to to the control modifier on macos (the only platform that didn't mess this up) lose its original purpose. Then the Windows Developers with their weird usage of control win.

Of course if you see control primarily as a shortcut button my stubbornness about this might seem a bit weird.😅

**Pull request closed without merging**
