### PR TITLE
Update dependencies: toml_edit, xshell, lsp_*

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Review by tronical — APPROVED** [review]

**Review by hunger — APPROVED** [review]
xshell gets better and better;-)

**Comment by ogoffart** [comment]
>  error: package `xshell v0.2.1` cannot be built because it requires rustc 1.59 or newer, while the currently active rustc version is 1.56.1

Same with kstring which is used by the new version of toml_edit which which is used by slint-build

This increase the MSRV for the rust crates.  But would not impact the MSRV for C++.

Option:
 1. Update our MSRV to 1.59 now
 2. Update the MSRV for the rust crate, but not for the C++ build
 3. Don't merge the slint-build part or make it optional  (it is only used for the MCU build flags anyway), and don't build xtask in the CI
 4. Don't upgrade anything that needs a newer MSRV

**Comment by ogoffart** [comment]
Added a commit that increase the MSRV

**Review by hunger — APPROVED** [review]
Fine with me:-)

**Pull request merged**
