### PR TITLE
Add `VecModel::replace` and `VecModel::replace_cloned`

### LINKED ISSUE #1045: Ability to replace inner `Vec` in `VecModel`
In my application, fairly often, I don't just need to remove an item from a list and add another one; I need to replace the list with an entirely separate list. I could use `set_<model name>` instead, but then I also have to reset every other function that had the `ModelRc` cloned... needless to say, this is complicated, and it seems like there should be a better way.

It seems like it wouldn't be too hard to have a function to replace the `Vec` in a `VecModel` with an entirely new `Vec`; is there anything that would be blocking this? If not, I could implement it probably.

~~Edit: It would also be useful to read the inner `Vec` for other purposes, like finding an element with a certain ID.~~ Solved with `Model::iter()`

_Originally posted by @rdrpenguin04 in https://github.com/slint-ui/slint/discussions/1043_

### PR DESCRIPTION
**Pull request by rdrpenguin04**
Closes #1045.

~~Incomplete; hasn't been fully tested. I'm working on testing with my project to see if it can at least remove the entire list successfully.~~

Edit: Has been tested; seems to work without crashing.

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks a lot for the contribution.
I wonder if `replace` is the right name for it. Maybe `set_vec` would be a better name.
(But that's just bikeshedding.)
I think however the replace_cloned is superfluous. Maybe one can take a `impl Into<Vec<T>>` as argument of `replace` (or `set_vec`) instead?

**Comment by tronical** [comment]
> Thanks a lot for the contribution.
> I wonder if `replace` is the right name for it. Maybe `set_vec` would be a better name.
> (But that's just bikeshedding.)

This might situation where we can either choose a model specific name (`set_vec` has my vote) or one that we'll re-use across different models (static polymorphism style). In the latter case we could go for `set_contents` or `set_data`.

> I think however the replace_cloned is superfluous. Maybe one can take a `impl Into<Vec<T>>` as argument of `replace` (or `set_vec`) instead?

I agree with that. So something like `fn set_vec(&mut self, data: impl Into<Vec<T>>);`.

**Comment by rdrpenguin04** [comment]
Alright; I could go with `set_vec` for now, and we could change it to `set_data` if we later move it into the trait. I'll get that done and squash.

**Comment by tronical** [comment]
Thanks, that looks good to me. Would you mind adding a test for the new function further down in model.rs? Thanks :)

(An entry in the ChangeLog file would be nice, too - but I can also add that later :)

**Review by tronical — APPROVED** [review]
Thank you for your patch! :)

**Comment by rdrpenguin04** [comment]
Thank you; happy to help!

**Pull request merged**
