### PR TITLE
LSP: code action for wrapping a string in `@tr()`

### PR DESCRIPTION
**Pull request by ogoffart**
It only suggest the transformation for string that are directly within an expression, so that's only string literals. (Not import, not image macro, not already translated strings)

Drive by fix: fix the code action for showing the preview that was broken because confusion between path and URL

### CODE REVIEW

**Review by tronical — APPROVED** [review]
Nice! Will this offer the action on a literal that's already surrounded by tr?

**Comment by ogoffart** [comment]
> Nice! Will this offer the action on a literal that's already surrounded by tr?

Nope. (see commit message: "not already translated strings")

**Comment by tronical** [comment]
"wraping" -> "wrapping" :)

**Comment by tronical** [comment]
> > Nice! Will this offer the action on a literal that's already surrounded by tr?
> 
> Nope. (see commit message: "not already translated strings")

Ahh alright. No problem.

**Pull request merged**
