### PR TITLE
Added icon and colorize-icon to LineEdit

### LINKED ISSUE #4505: Add `icon` property to line edit.
Mostly to show the context of a text input without describing it with a label, text input provides a leading icon e.g. for displaying it is a search or a password input element. To provide this in the  `std-widgets` LineEdit it would be good to have an `icon` property and a `colorize` property similar to `Button`.

### PR DESCRIPTION
**Pull request by FloVanGH**
Fixes #4505

### CODE REVIEW

**Comment by FloVanGH** [comment]
> Wasn't the *input-type` supposed to e.g. add a looking glass for a (to be defined!) "search" input type?
> 
> Well, this functionality can certainly be used to implement such kind of behavior.

I don't think the icon should depend on the input type. You may want to define a custom icon, don't show an icon or something else.

**Comment by ogoffart** [comment]
When we get a "search" input type, we can set a default search icon if none is set.


My question is: does this follow the guidelines from fluent, material, cosmic design system?
which of them include an icon in the line edit?

**Comment by FloVanGH** [comment]
> When we get a "search" input type, we can set a default search icon if none is set.
> 
> My question is: does this follow the guidelines from fluent, material, cosmic design system? which of them include an icon in the line edit?

All styles provides an icon. Some of them even a secondary icon. But I would start with support of one. I would keep it simple and don't make the icon depend on the input type, also if it is default behavior. Just set the icon you want from outside, similar to button.

**Comment by FloVanGH** [comment]
I close this because maybe this will handle differently in the future check #4505  and #4518. The branch will remain, because some parts of the code could be reused.

**Pull request closed without merging**
