### PR TITLE
Rename the compat-0-2-0 feature to compat-0.3.0

### PR DESCRIPTION
**Pull request by ogoffart**
But keep a compat-0-2-0 fome compatibility anyway

### CODE REVIEW

**Comment by ogoffart** [comment]
The alternatives could be:
 - Keep it compat-0-2-0
 - use another name that doesn't have the version, such as  `compat1` or `default1`
 - Remove entirely since we didn't make use of this in the 0.2 lifetime and we could just as well change the semver version at this point.

**Comment by hunger** [comment]
* **`compat-0.3.0` only:** Makes sense to me.
* **`compat-0.2.0` only:** Makes no sense to me. We bumped the minor version because the API is not compatible and the feature will not change that.
* **`compat1`:** Adds overhead for users that have to look up which compat feature to enable
* **semevr only:** Makes sense to me -- bonus for one item less to check on release.

**Comment by tronical** [comment]
I'm with Tobias on this one. This is an opportunity to introduce the feature name with dots, as we found out only afterwards.

**Comment by ogoffart** [comment]
> compat1: Adds overhead for users that have to look up which compat feature to enable

I think this overhead already exist whatever name we pick (because when we release v0.3.1 and we don't need to add a default feature, then it stays compat-0.3.0

**Review by tronical — APPROVED** [review]

**Pull request merged**
