### PR TITLE
Update examples to new syntax

### PR DESCRIPTION
**Pull request by FloVanGH**
* Update examples to new syntax
* Do some manual adjustments on widgets

### CODE REVIEW

**Comment by ogoffart** [comment]
it would be nice to split this into two commit if possible so I can see the difference between the automatic stuff and the manual stuff.
Is that easy for you?

**Comment by FloVanGH** [comment]
@ogoffart sure will do it. Good suggestion!

**Comment by FloVanGH** [comment]
@ogoffart this includes now only the syntax updater changes. The manual changes will follow soon. I will give an update after it is done.

**Comment by FloVanGH** [comment]
@ogoffart the changes are ready now.

**Review by ogoffart — APPROVED** [review]

**Pull request merged**
