### PR TITLE
internal: remove per-item cache fields

### PR DESCRIPTION
**Pull request by tronical**
All the renderers are storing their caches such as textures, fonts, etc. for items in the separate per-component-per-item hash table, except for the partial renderer. This change ports the partial renderer over and removes the now unnecessary fields and data structures.

### CODE REVIEW

**Comment by tronical** [comment]
Not for the release as well :-)

**Comment by ogoffart** [comment]
> we could use another hash table on mcu that supports no_std?

Yes, we could.

Another idea would be to add a Box in the "object tree" Component, accessible with the ComponentVTable.

**Comment by tronical** [comment]
> > we could use another hash table on mcu that supports no_std?
> 
> Yes, we could.
> 
> Another idea would be to add a Box in the "object tree" Component, accessible with the ComponentVTable.

Right now I think we still have only one cache per renderer combination, so that would work. But I think if we wanted to use the partial renderer together with say Skia, then one box would in the component would not be sufficient.

My preference is a no_std hash table.

**Comment by ogoffart** [comment]
> Right now I think we still have only one cache per renderer combination, so that would work. But I think if we wanted to use the partial renderer together with say Skia, then one box would in the component would not be sufficient.

The Box could be a `Box<Caches>` where the caches holds both caches for the Skia and the renderer. 
(Or a `Box<dyn Any>` where each renderer put whatever they like. And the skia renderer can put both a cache for the graphics and a cache for the partial rendering.

**Comment by tronical** [comment]
You're right. That is the better approach. One hash table less. And for the partial renderer instead of a hash on item index to logical rect, it could just be a vec of logical rects, as every item is tracked anyway (as opposed to only some items in the renderer attaching resources).

**Pull request closed without merging**
