### PR TITLE
Tree sitter update 1.0

### PR DESCRIPTION
**Pull request by hunger**
This obviously needs some squashing ;-)

### CODE REVIEW

**Comment by tronical** [comment]
Very cool. 38k of additional source is a lot though. Mostly from tests that test behavior.

This could perhaps be cut on half by printing only the expression tree and omitting the Slint sources. Instead you could store the sha1 of the commit used to generate and you can retrieve the source with git cat-file.

**Comment by jrmoulton** [comment]
Awesome! I'll check it out

**Comment by jrmoulton** [comment]
> @jrmoulton I did try to add you as reviewer, but Github would not let me put you into the reviewer field, so I @-mentioned you only. Sorry for that!

No worries :)

> I personally would prefer either moving the corpus into a git submodule or to move the entire tree-sitter parser into its own repository. It's harder to find there, but most users will consume that code via a DB of available parsers built into their editors anyway. So I think that is fine.

I would vote for moving it to its own repository. For compatibility with projects such as nvim-treesitter it is recommended to have the project be in its own repository. This is actually the reason I never actually got changed nvim-treesitter from pointing to jrmoulton/tree-sitter-slint. And it would probably be easier to give me permissions on a separate repository as well so I could help stay on top of issues/pull requests.

**Comment by jrmoulton** [comment]
Looking at the output of the AST in the tests I think there is some room for slimming down the specificity on leaf nodes. When I originally wrote the tree-sitter-slint grammar I didn't really understand how much detail was necessary in order to take advantage of the query system. But for all of the use cases of tree-sitter that I've seen there isn't any benefit to adding more detail than is necessary to match highlights. And slimming down can pretty quickly reduce the complexity of the printed AST in tests and makes diffing much more maintainable.

**Comment by tronical** [comment]
You could still generate the files the tooling expects from a smaller set of files (as suggested), before running the test tool. Or does the tree sitter tooling use/require git?

**Comment by tronical** [comment]
> @tronical: I could check in a tar all, that would be smaller. Or write, test and maintain a script that does something clever like checking out the tests in a certain version, combining them with the tree-sitter AST stored somewhere (still more than half the size of the tests).

That’s exactly what I was thinking of (the script approach).

> Plus any editor grabbing the sources and trying to run the tests will either fail or not get proper results as `tree-sitter test` will not run the test case generator.

Is there a use case for other editors running tests of the Slint grammar?

> Of course putting the tests into a git submodule has the same problem.

Yep.

I’m a fan of mono repos, so I’m interested in a solution that reduces size and allows keeping this in the same repo. I’m confident about a solution for @jrmoulton in terms of permissions.

**Comment by ogoffart** [comment]
It is a bit overkill to take all the tests in the repository that are testing the runtime behavior of Slint application to make them parser tests.  I believe you didn't review them all manually to check that the result is actually working.
Maybe it would be ok to keep with a subset of cases/tests that are low level.

**Comment by jrmoulton** [comment]
Another option would be to build a script that just parses the langref.md document. If I'm not wrong that document stays up to date with all of the language syntax with examples correct? If that's the case then using that as the source of all tests would lead to a better set simple and clear tests.

**Comment by ogoffart** [comment]
The test on the CI could just run the test generator with all the files in test/cases to generate the corpus.

`tree-sitter test` would just not test everything by default for users.  We should just have a small subset for these.

**Pull request merged**
