### PR TITLE
Fix #5565

### LINKED ISSUE #5565: Auto disable maximize button when window resize is disabled
Currently when ```width``` and ```height``` properties of the ```Window``` are set, resizing is automatically disabled, this is expected behavior. what is not expected is the maximize button stays enabled which defies the purpose of setting hard window dimensions.

### PR DESCRIPTION
**Pull request by teknalb**
Fix/workaround for #5565

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]
Thanks for the PR.

This looks good to me.

(Note that this might be conflicting with https://github.com/slint-ui/slint/pull/6675 it if it merged.)

**Comment by ogoffart** [comment]
This will do.

**Comment by teknalb** [comment]
Hi,

This fix is broken in Slint `1.12.0` and `1.12.1`

**Comment by tronical** [comment]
Thanks, I can see why. `set_resizable` is called when there's no window yet, so this worked by accident.

**Pull request merged**
