### PR TITLE
ci: Move some code out opf the docs pass so updating to docs.tng will be easier:-)

### PR DESCRIPTION
**Pull request by hunger**
A few CI changes to have less work updating the docs scripts :-)

### CODE REVIEW

**Comment by ogoffart** [comment]
The reason it was in the same job is because then we don't rebuild xtask several times in different job.
But if the documentation build will no longer be in xtask, then it doesn't matter.

**Comment by hunger** [comment]
It will continue to run xtasks... But also build a lot of slint for the screenshot tool it uses :-/

**Comment by hunger** [comment]
I need to think about this... the screenshot tool takes ages to build. maybe we can build that and the xtask in a separate step and just deploy it into the build steps that need it so that it only needs to run in there.

**Comment by hunger** [comment]
Does not apply anymore.

**Pull request closed without merging**
