### PR TITLE
Fix timer not firing on Windows

### LINKED ISSUE #3875: Timer example does not work correctly on current branch
### Discussed in https://github.com/slint-ui/slint/discussions/3873

<div type='discussions-op-text'>

<sup>Originally posted by **HitecExports** November  7, 2023</sup>
Hello!

Platform: Windows 11
Rust 1.73
slint = { git = "https://github.com/slint-ui/slint.git", branch = "master" }

Timer example does not work properly in current slint branch

"Elapsed Time" progress bar updates only while moving mouse in any area (even outside the main window)

**So timer does not fire event automatically.**

I noticed this problem for a week ago.

Before there were no such problem.

**On Slint 1.2.2 same Timer Example works fine**

image

Code (copied from Timer example)

```
// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
use slint::{Timer, TimerMode};

slint::slint!(

    import { LineEdit, Button, Slider, HorizontalBox, VerticalBox } from "std-widgets.slint";

    export component MainWindow inherits Window {
        in-out property <duration> total-time: slider.value * 1s;
        in-out property <duration> elapsed-time;

        callback tick(duration);
        tick(passed-time) => {
            root.elapsed-time += passed-time;
            root.elapsed-time = min(root.elapsed-time, root.total-time);
        }

        VerticalBox {
            HorizontalBox {
                padding-left: 0;
                Text { text: "Elapsed Time:"; }
                Rectangle {
                    min-width: 200px;
                    max-height: 30px;
                    background: gray;
                    Rectangle {
                        x:0;
                        height: 100%;
                        width: parent.width * (root.elapsed-time/root.total-time);
                        background: lightblue;
                    }
                }
            }
            Text{
                text: (root.total-time / 1s) + "s";
            }
            HorizontalBox {
                padding-left: 0;
                Text {
                    text: "Duration:";
                    vertical-alignment: center;
                }
                slider := Slider {
                    maximum: 30s / 1s;
                    value: 10s / 1s;
                    changed(new-duration) => {
                        root.total-time = new-duration * 1s;
                        root.elapsed-time = min(root.elapsed-time, root.total-time);
                    }
                }
            }
            Button {
                text: "Reset";
                clicked => {
                    root.elapsed-time = 0
                }
            }
        }
    }
);

pub fn main() {
    let main_window = MainWindow::new().unwrap();
    let timer = Timer::default();
    {
        let main_window_weak = main_window.as_weak();
        timer.start(
            TimerMode::Repeated,
            std::time::Duration::from_millis(10),
            move || {
                let main_window = main_window_weak.unwrap();
                main_window.invoke_tick(10);
            },
        );
    }
    main_window.run().unwrap();
}
```
</div>

### PR DESCRIPTION
**Pull request by ogoffart**
If we set the control flow to Wait, winit will always wait even if we set the control flow later to some smaller timeout in the AboutToWait event.
Wait is the default anyway in winit 0.29 so this is not required

I'd say this is a bug in winit, but we can easily work it around

Fix #3875

### CODE REVIEW

**Review by tronical — APPROVED** [review]
Very weird that this … works. Any idea why?

**Comment by ogoffart** [comment]
> Wait is the default anyway in winit 0.29 so this is not required

No this is wrong.  the default on windows is whatever was set last.

> Any idea why?

It works because the patch is wrong, and with this we would never wait.

I think the bug is really in winit

**Comment by ogoffart** [comment]
Made a new patch

**Review by tronical — APPROVED** [review]

**Comment by ogoffart** [comment]
https://github.com/rust-windowing/winit/pull/3216 was merged. But I'll merge this as well so we have a fix for the release. Will revert once next version of winit is released

**Pull request merged**
