### PR TITLE
Permit rotation properties on Text elements without children

### PR DESCRIPTION
**Pull request by tronical**
This works with Skia, Qt, and FemtoVG.

cc #1481

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]
Can you add a rotated Text in tests/cases/examples/rotate.slint ?

**Comment by tronical** [comment]
Sure :)

**Review by ogoffart — COMMENTED** [review]
Should probably have been documented somewhere

**Comment by tronical** [comment]
Oops. Fixed in bc458ebb267359f7fd19179d491f30db40c6486b

**Pull request merged**
